/* Banco de lugares do "Cadê no Mapa?"
 * Cada nível tem um pool de 50 lugares; o desafio diário sorteia 5 de cada
 * pool usando a data como semente — todo mundo joga o mesmo desafio no dia.
 * lat/lng em graus decimais. cat: capital | cidade | turistico | natureza
 * O mapa vai de 84°N a 56°S: nenhuma coordenada pode sair dessa faixa.
 */
window.LEVELS = [
  {
    name: 'Gigantes do Mapa',
    desc: 'Cidades que todo mundo já viu em filme. Aquecimento!',
    time: 10,
    places: [
      { name: 'Rio de Janeiro', country: 'Brasil', flag: '🇧🇷', cat: 'cidade', lat: -22.91, lng: -43.17, fact: 'Tem a maior floresta urbana do mundo, a Floresta da Tijuca.' },
      { name: 'São Paulo', country: 'Brasil', flag: '🇧🇷', cat: 'cidade', lat: -23.55, lng: -46.63, fact: 'É a maior cidade do hemisfério sul.' },
      { name: 'Paris', country: 'França', flag: '🇫🇷', cat: 'capital', lat: 48.86, lng: 2.35, fact: 'A Torre Eiffel cresce até 15 cm no verão por causa do calor.' },
      { name: 'Nova York', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 40.71, lng: -74.01, fact: 'Mais de 800 idiomas são falados na cidade — recorde mundial.' },
      { name: 'Londres', country: 'Reino Unido', flag: '🇬🇧', cat: 'capital', lat: 51.51, lng: -0.13, fact: 'O Big Ben é o nome do sino, não da torre.' },
      { name: 'Tóquio', country: 'Japão', flag: '🇯🇵', cat: 'capital', lat: 35.68, lng: 139.69, fact: 'É a maior região metropolitana do mundo: mais de 37 milhões de pessoas.' },
      { name: 'Sydney', country: 'Austrália', flag: '🇦🇺', cat: 'cidade', lat: -33.87, lng: 151.21, fact: 'A Opera House tem mais de 1 milhão de telhas no telhado.' },
      { name: 'Moscou', country: 'Rússia', flag: '🇷🇺', cat: 'capital', lat: 55.76, lng: 37.62, fact: 'O metrô é tão ornamentado que ganhou o apelido de "palácio subterrâneo".' },
      { name: 'Cairo', country: 'Egito', flag: '🇪🇬', cat: 'capital', lat: 30.04, lng: 31.24, fact: 'É a maior cidade da África e do mundo árabe.' },
      { name: 'Roma', country: 'Itália', flag: '🇮🇹', cat: 'capital', lat: 41.9, lng: 12.5, fact: 'Jogam cerca de 1,5 milhão de euros por ano na Fontana di Trevi.' },
      { name: 'Pequim', country: 'China', flag: '🇨🇳', cat: 'capital', lat: 39.9, lng: 116.4, fact: 'A Cidade Proibida tem 8.700 salas e quase 1 milhão de relíquias.' },
      { name: 'Buenos Aires', country: 'Argentina', flag: '🇦🇷', cat: 'capital', lat: -34.6, lng: -58.38, fact: 'Tem a avenida mais larga do mundo: a 9 de Julio, com 16 pistas.' },
      { name: 'Cidade do México', country: 'México', flag: '🇲🇽', cat: 'capital', lat: 19.43, lng: -99.13, fact: 'Foi construída sobre um lago e afunda cerca de 50 cm por ano.' },
      { name: 'Los Angeles', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 34.05, lng: -118.24, fact: 'O letreiro de Hollywood originalmente dizia "Hollywoodland".' },
      { name: 'Chicago', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 41.88, lng: -87.63, fact: 'O primeiro arranha-céu do mundo nasceu lá, em 1885.' },
      { name: 'Toronto', country: 'Canadá', flag: '🇨🇦', cat: 'cidade', lat: 43.65, lng: -79.38, fact: 'A CN Tower foi a estrutura mais alta do mundo por 32 anos.' },
      { name: 'Dubai', country: 'Emirados Árabes', flag: '🇦🇪', cat: 'cidade', lat: 25.2, lng: 55.27, fact: 'Do alto do Burj Khalifa dá para ver o pôr do sol duas vezes no mesmo dia.' },
      { name: 'Singapura', country: 'Singapura', flag: '🇸🇬', cat: 'capital', lat: 1.35, lng: 103.82, fact: 'É proibido vender chiclete na cidade-estado.' },
      { name: 'Hong Kong', country: 'China', flag: '🇭🇰', cat: 'cidade', lat: 22.32, lng: 114.17, fact: 'Tem mais arranha-céus que qualquer outra cidade do mundo.' },
      { name: 'Amsterdã', country: 'Países Baixos', flag: '🇳🇱', cat: 'capital', lat: 52.37, lng: 4.9, fact: 'Há mais bicicletas que habitantes na cidade.' },
      { name: 'Veneza', country: 'Itália', flag: '🇮🇹', cat: 'cidade', lat: 45.44, lng: 12.34, fact: 'São 118 ilhas, 400 pontes e nenhum carro.' },
      { name: 'Las Vegas', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 36.17, lng: -115.14, fact: 'É o ponto mais brilhante da Terra visto do espaço.' },
      { name: 'Jerusalém', country: 'Israel', flag: '🇮🇱', cat: 'cidade', lat: 31.78, lng: 35.22, fact: 'Cidade sagrada para três religiões ao mesmo tempo.' },
      { name: 'Havana', country: 'Cuba', flag: '🇨🇺', cat: 'capital', lat: 23.11, lng: -82.37, fact: 'Carros americanos dos anos 1950 ainda rodam pelas ruas.' },
      { name: 'Berlim', country: 'Alemanha', flag: '🇩🇪', cat: 'capital', lat: 52.52, lng: 13.4, fact: 'Tem mais pontes que Veneza: cerca de 1.700.' },
      { name: 'Madri', country: 'Espanha', flag: '🇪🇸', cat: 'capital', lat: 40.42, lng: -3.7, fact: 'Abriga o restaurante mais antigo do mundo em funcionamento (1725).' },
      { name: 'Barcelona', country: 'Espanha', flag: '🇪🇸', cat: 'cidade', lat: 41.39, lng: 2.17, fact: 'A Sagrada Família está em obras desde 1882.' },
      { name: 'Lisboa', country: 'Portugal', flag: '🇵🇹', cat: 'capital', lat: 38.72, lng: -9.14, fact: 'É mais antiga que Roma: tem mais de 3 mil anos.' },
      { name: 'Xangai', country: 'China', flag: '🇨🇳', cat: 'cidade', lat: 31.23, lng: 121.47, fact: 'Tem o trem comercial mais rápido do mundo: o Maglev, a 431 km/h.' },
      { name: 'Seul', country: 'Coreia do Sul', flag: '🇰🇷', cat: 'capital', lat: 37.57, lng: 126.98, fact: 'Metade da população do país vive na sua região metropolitana.' },
      { name: 'Bangkok', country: 'Tailândia', flag: '🇹🇭', cat: 'capital', lat: 13.76, lng: 100.5, fact: 'Seu nome cerimonial completo tem 168 letras — o mais longo do mundo.' },
      { name: 'Istambul', country: 'Turquia', flag: '🇹🇷', cat: 'cidade', lat: 41.04, lng: 28.98, fact: 'É a única grande cidade do mundo em dois continentes ao mesmo tempo.' },
      { name: 'Miami', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 25.76, lng: -80.19, fact: 'É a única grande cidade dos EUA fundada por uma mulher.' },
      { name: 'São Francisco', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 37.77, lng: -122.42, fact: 'A ponte Golden Gate é repintada continuamente, o ano inteiro.' },
      { name: 'Mumbai', country: 'Índia', flag: '🇮🇳', cat: 'cidade', lat: 19.08, lng: 72.88, fact: 'Produz mais filmes por ano que Hollywood — é a casa de Bollywood.' },
      { name: 'Atenas', country: 'Grécia', flag: '🇬🇷', cat: 'capital', lat: 37.98, lng: 23.73, fact: 'É habitada continuamente há mais de 5 mil anos.' },
      { name: 'Viena', country: 'Áustria', flag: '🇦🇹', cat: 'capital', lat: 48.21, lng: 16.37, fact: 'Eleita várias vezes a cidade com melhor qualidade de vida do mundo.' },
      { name: 'Praga', country: 'Tchéquia', flag: '🇨🇿', cat: 'capital', lat: 50.08, lng: 14.44, fact: 'Seu relógio astronômico de 600 anos ainda funciona.' },
      { name: 'Dublin', country: 'Irlanda', flag: '🇮🇪', cat: 'capital', lat: 53.35, lng: -6.26, fact: 'O portão da cervejaria Guinness tem contrato de aluguel de 9 mil anos.' },
      { name: 'Bruxelas', country: 'Bélgica', flag: '🇧🇪', cat: 'capital', lat: 50.85, lng: 4.35, fact: 'É a capital de facto da União Europeia.' },
      { name: 'Milão', country: 'Itália', flag: '🇮🇹', cat: 'cidade', lat: 45.46, lng: 9.19, fact: 'Sua catedral gótica levou quase 600 anos para ficar pronta.' },
      { name: 'Munique', country: 'Alemanha', flag: '🇩🇪', cat: 'cidade', lat: 48.14, lng: 11.58, fact: 'A Oktoberfest começa, na verdade, em setembro.' },
      { name: 'Brasília', country: 'Brasil', flag: '🇧🇷', cat: 'capital', lat: -15.79, lng: -47.88, fact: 'Construída em 41 meses; vista do alto, tem forma de avião.' },
      { name: 'Washington, D.C.', country: 'Estados Unidos', flag: '🇺🇸', cat: 'capital', lat: 38.91, lng: -77.04, fact: 'Nenhum prédio pode ser mais alto que o Capitólio, por lei.' },
      { name: 'Nova Délhi', country: 'Índia', flag: '🇮🇳', cat: 'capital', lat: 28.61, lng: 77.21, fact: 'Délhi já foi capital de pelo menos 7 impérios diferentes.' },
      { name: 'Melbourne', country: 'Austrália', flag: '🇦🇺', cat: 'cidade', lat: -37.81, lng: 144.96, fact: 'Foi a capital da Austrália por 26 anos antes de Canberra.' },
      { name: 'Vancouver', country: 'Canadá', flag: '🇨🇦', cat: 'cidade', lat: 49.28, lng: -123.12, fact: 'Dá para esquiar e velejar no mesmo dia na cidade.' },
      { name: 'Cidade do Cabo', country: 'África do Sul', flag: '🇿🇦', cat: 'cidade', lat: -33.92, lng: 18.42, fact: 'A Table Mountain tem mais espécies de plantas que o Reino Unido inteiro.' },
      { name: 'Estocolmo', country: 'Suécia', flag: '🇸🇪', cat: 'capital', lat: 59.33, lng: 18.07, fact: 'A cidade é construída sobre 14 ilhas.' },
      { name: 'Copenhague', country: 'Dinamarca', flag: '🇩🇰', cat: 'capital', lat: 55.68, lng: 12.57, fact: 'A estátua da Pequena Sereia tem só 1,25 m de altura.' },
    ],
  },
  {
    name: 'Capitais Famosas',
    desc: 'Capitais do noticiário. Você sabe o nome — mas sabe o lugar?',
    time: 10,
    places: [
      { name: 'Ottawa', country: 'Canadá', flag: '🇨🇦', cat: 'capital', lat: 45.42, lng: -75.7, fact: 'No inverno, o canal Rideau vira a maior pista de patinação do mundo.' },
      { name: 'Canberra', country: 'Austrália', flag: '🇦🇺', cat: 'capital', lat: -35.28, lng: 149.13, fact: 'Criada do zero para encerrar a briga entre Sydney e Melbourne.' },
      { name: 'Wellington', country: 'Nova Zelândia', flag: '🇳🇿', cat: 'capital', lat: -41.29, lng: 174.78, fact: 'É a capital mais ao sul do mundo — e a mais ventosa.' },
      { name: 'Oslo', country: 'Noruega', flag: '🇳🇴', cat: 'capital', lat: 59.91, lng: 10.75, fact: 'Entrega o Prêmio Nobel da Paz todo ano desde 1901.' },
      { name: 'Helsinque', country: 'Finlândia', flag: '🇫🇮', cat: 'capital', lat: 60.17, lng: 24.94, fact: 'Tem uma igreja escavada dentro de uma rocha gigante.' },
      { name: 'Varsóvia', country: 'Polônia', flag: '🇵🇱', cat: 'capital', lat: 52.23, lng: 21.01, fact: 'Seu centro histórico foi reconstruído tijolo por tijolo após a guerra.' },
      { name: 'Budapeste', country: 'Hungria', flag: '🇭🇺', cat: 'capital', lat: 47.5, lng: 19.04, fact: 'São duas cidades, Buda e Peste, separadas pelo Danúbio.' },
      { name: 'Bucareste', country: 'Romênia', flag: '🇷🇴', cat: 'capital', lat: 44.43, lng: 26.1, fact: 'O Palácio do Parlamento é o prédio mais pesado do mundo.' },
      { name: 'Sófia', country: 'Bulgária', flag: '🇧🇬', cat: 'capital', lat: 42.7, lng: 23.32, fact: 'Uma das capitais mais antigas da Europa, aos pés do monte Vitosha.' },
      { name: 'Zagreb', country: 'Croácia', flag: '🇭🇷', cat: 'capital', lat: 45.81, lng: 15.98, fact: 'Tem um Museu dos Relacionamentos Rompidos.' },
      { name: 'Belgrado', country: 'Sérvia', flag: '🇷🇸', cat: 'capital', lat: 44.79, lng: 20.45, fact: 'Foi destruída e reconstruída mais de 40 vezes em 2 mil anos.' },
      { name: 'Kiev', country: 'Ucrânia', flag: '🇺🇦', cat: 'capital', lat: 50.45, lng: 30.52, fact: 'Fundada no século 5, é uma das cidades mais antigas do Leste Europeu.' },
      { name: 'Minsk', country: 'Bielorrússia', flag: '🇧🇾', cat: 'capital', lat: 53.9, lng: 27.57, fact: 'Foi reconstruída quase inteira no estilo monumental soviético.' },
      { name: 'Riga', country: 'Letônia', flag: '🇱🇻', cat: 'capital', lat: 56.95, lng: 24.11, fact: 'Tem a maior coleção de arquitetura art nouveau do mundo.' },
      { name: 'Vilnius', country: 'Lituânia', flag: '🇱🇹', cat: 'capital', lat: 54.69, lng: 25.28, fact: 'O bairro de artistas Užupis se declarou "república independente".' },
      { name: 'Tallinn', country: 'Estônia', flag: '🇪🇪', cat: 'capital', lat: 59.44, lng: 24.75, fact: 'Um dos centros medievais mais bem preservados da Europa.' },
      { name: 'Berna', country: 'Suíça', flag: '🇨🇭', cat: 'capital', lat: 46.95, lng: 7.45, fact: 'Muita gente acha que a capital é Zurique ou Genebra — é Berna.' },
      { name: 'Lima', country: 'Peru', flag: '🇵🇪', cat: 'capital', lat: -12.05, lng: -77.04, fact: 'É a segunda maior cidade do mundo construída num deserto.' },
      { name: 'Bogotá', country: 'Colômbia', flag: '🇨🇴', cat: 'capital', lat: 4.71, lng: -74.07, fact: 'Fica a 2.640 m de altitude, uma das capitais mais altas do mundo.' },
      { name: 'Santiago', country: 'Chile', flag: '🇨🇱', cat: 'capital', lat: -33.45, lng: -70.66, fact: 'Dá para esquiar nos Andes e surfar no Pacífico no mesmo dia.' },
      { name: 'Caracas', country: 'Venezuela', flag: '🇻🇪', cat: 'capital', lat: 10.49, lng: -66.88, fact: 'Fica num vale estreito separado do mar pelo monte Ávila.' },
      { name: 'Quito', country: 'Equador', flag: '🇪🇨', cat: 'capital', lat: -0.18, lng: -78.47, fact: 'Foi o primeiro centro histórico tombado pela UNESCO, em 1978.' },
      { name: 'La Paz', country: 'Bolívia', flag: '🇧🇴', cat: 'capital', lat: -16.49, lng: -68.15, fact: 'A sede de governo mais alta do mundo usa teleférico como transporte público.' },
      { name: 'Montevidéu', country: 'Uruguai', flag: '🇺🇾', cat: 'capital', lat: -34.9, lng: -56.16, fact: 'Quase metade dos uruguaios vive na capital.' },
      { name: 'Assunção', country: 'Paraguai', flag: '🇵🇾', cat: 'capital', lat: -25.28, lng: -57.63, fact: 'É chamada de "mãe das cidades" da América do Sul.' },
      { name: 'Nairóbi', country: 'Quênia', flag: '🇰🇪', cat: 'capital', lat: -1.29, lng: 36.82, fact: 'Tem um parque nacional com leões e girafas dentro da cidade.' },
      { name: 'Adis Abeba', country: 'Etiópia', flag: '🇪🇹', cat: 'capital', lat: 9.03, lng: 38.74, fact: 'Sede da União Africana, a 2.355 m de altitude.' },
      { name: 'Pretória', country: 'África do Sul', flag: '🇿🇦', cat: 'capital', lat: -25.75, lng: 28.19, fact: 'A África do Sul tem três capitais — esta é a administrativa.' },
      { name: 'Rabat', country: 'Marrocos', flag: '🇲🇦', cat: 'capital', lat: 34.02, lng: -6.84, fact: 'Muita gente chuta Casablanca ou Marrakech, mas a capital é Rabat.' },
      { name: 'Túnis', country: 'Tunísia', flag: '🇹🇳', cat: 'capital', lat: 36.81, lng: 10.18, fact: 'As ruínas de Cartago ficam a poucos quilômetros do centro.' },
      { name: 'Argel', country: 'Argélia', flag: '🇩🇿', cat: 'capital', lat: 36.75, lng: 3.06, fact: 'Capital do maior país da África em território.' },
      { name: 'Trípoli', country: 'Líbia', flag: '🇱🇾', cat: 'capital', lat: 32.89, lng: 13.19, fact: 'Fundada pelos fenícios no século 7 a.C.' },
      { name: 'Abuja', country: 'Nigéria', flag: '🇳🇬', cat: 'capital', lat: 9.06, lng: 7.49, fact: 'Capital planejada que substituiu Lagos em 1991.' },
      { name: 'Acra', country: 'Gana', flag: '🇬🇭', cat: 'capital', lat: 5.6, lng: -0.19, fact: 'O país já se chamou Costa do Ouro, pela riqueza do metal.' },
      { name: 'Dakar', country: 'Senegal', flag: '🇸🇳', cat: 'capital', lat: 14.72, lng: -17.47, fact: 'Fica no ponto mais ocidental de toda a África continental.' },
      { name: 'Teerã', country: 'Irã', flag: '🇮🇷', cat: 'capital', lat: 35.69, lng: 51.39, fact: 'Fica aos pés dos montes Alborz, com picos de mais de 5.000 m.' },
      { name: 'Bagdá', country: 'Iraque', flag: '🇮🇶', cat: 'capital', lat: 33.31, lng: 44.36, fact: 'No século 9 era a maior cidade do mundo.' },
      { name: 'Riade', country: 'Arábia Saudita', flag: '🇸🇦', cat: 'capital', lat: 24.71, lng: 46.68, fact: 'Passou de cidade murada a metrópole de 7 milhões em 70 anos.' },
      { name: 'Amã', country: 'Jordânia', flag: '🇯🇴', cat: 'capital', lat: 31.95, lng: 35.93, fact: 'Construída sobre sete colinas, como Roma.' },
      { name: 'Beirute', country: 'Líbano', flag: '🇱🇧', cat: 'capital', lat: 33.89, lng: 35.5, fact: 'Já foi chamada de "a Paris do Oriente Médio".' },
      { name: 'Damasco', country: 'Síria', flag: '🇸🇾', cat: 'capital', lat: 33.51, lng: 36.29, fact: 'Disputa o título de cidade continuamente habitada mais antiga do mundo.' },
      { name: 'Doha', country: 'Catar', flag: '🇶🇦', cat: 'capital', lat: 25.29, lng: 51.53, fact: 'Sediou a primeira Copa do Mundo realizada no Oriente Médio.' },
      { name: 'Abu Dhabi', country: 'Emirados Árabes', flag: '🇦🇪', cat: 'capital', lat: 24.45, lng: 54.38, fact: 'A capital dos Emirados não é Dubai — é Abu Dhabi.' },
      { name: 'Kuala Lumpur', country: 'Malásia', flag: '🇲🇾', cat: 'capital', lat: 3.14, lng: 101.69, fact: 'O nome significa "confluência lamacenta".' },
      { name: 'Jacarta', country: 'Indonésia', flag: '🇮🇩', cat: 'capital', lat: -6.21, lng: 106.85, fact: 'Afunda tão rápido que o país decidiu construir outra capital.' },
      { name: 'Manila', country: 'Filipinas', flag: '🇵🇭', cat: 'capital', lat: 14.6, lng: 120.98, fact: 'É a cidade com maior densidade populacional do planeta.' },
      { name: 'Hanói', country: 'Vietnã', flag: '🇻🇳', cat: 'capital', lat: 21.03, lng: 105.85, fact: 'Tem uma rua onde o trem passa a centímetros das casas.' },
      { name: 'Islamabad', country: 'Paquistão', flag: '🇵🇰', cat: 'capital', lat: 33.68, lng: 73.05, fact: 'Capital planejada nos anos 1960, aos pés do Himalaia.' },
      { name: 'Cabul', country: 'Afeganistão', flag: '🇦🇫', cat: 'capital', lat: 34.53, lng: 69.17, fact: 'Fica num vale a 1.790 m, cercada pelas montanhas Hindu Kush.' },
      { name: 'Cidade do Vaticano', country: 'Vaticano', flag: '🇻🇦', cat: 'capital', lat: 41.9, lng: 12.45, fact: 'O menor país do mundo cabe inteiro dentro de Roma.' },
    ],
  },
  {
    name: 'Cartões-Postais',
    desc: 'Monumentos que você reconhece de olhos fechados. E de mapa aberto?',
    time: 10,
    places: [
      { name: 'Machu Picchu', country: 'Peru', flag: '🇵🇪', cat: 'turistico', lat: -13.16, lng: -72.55, fact: 'Construída no século 15 sem uso de rodas nem argamassa.' },
      { name: 'Cristo Redentor', country: 'Brasil', flag: '🇧🇷', cat: 'turistico', lat: -22.95, lng: -43.21, fact: 'É atingido por raios de 3 a 5 vezes por ano.' },
      { name: 'Grande Muralha da China', country: 'China', flag: '🇨🇳', cat: 'turistico', lat: 40.36, lng: 116.02, fact: 'Com todos os ramais, soma mais de 21 mil km.' },
      { name: 'Pirâmides de Gizé', country: 'Egito', flag: '🇪🇬', cat: 'turistico', lat: 29.98, lng: 31.13, fact: 'A Grande Pirâmide foi a construção mais alta do mundo por 3.800 anos.' },
      { name: 'Taj Mahal', country: 'Índia', flag: '🇮🇳', cat: 'turistico', lat: 27.17, lng: 78.04, fact: 'Mausoléu construído por um imperador para a esposa favorita.' },
      { name: 'Stonehenge', country: 'Reino Unido', flag: '🇬🇧', cat: 'turistico', lat: 51.18, lng: -1.83, fact: 'Algumas pedras vieram de 250 km de distância — ninguém sabe como.' },
      { name: 'Coliseu', country: 'Itália', flag: '🇮🇹', cat: 'turistico', lat: 41.89, lng: 12.49, fact: 'Podia ser inundado para simular batalhas navais.' },
      { name: 'Estátua da Liberdade', country: 'Estados Unidos', flag: '🇺🇸', cat: 'turistico', lat: 40.69, lng: -74.04, fact: 'Presente da França, chegou desmontada em 350 pedaços.' },
      { name: 'Chichén Itzá', country: 'México', flag: '🇲🇽', cat: 'turistico', lat: 20.68, lng: -88.57, fact: 'Bater palmas diante da pirâmide produz eco que imita um pássaro sagrado.' },
      { name: 'Petra', country: 'Jordânia', flag: '🇯🇴', cat: 'turistico', lat: 30.33, lng: 35.44, fact: 'A cidade inteira foi esculpida diretamente na rocha rosa.' },
      { name: 'Angkor Wat', country: 'Camboja', flag: '🇰🇭', cat: 'turistico', lat: 13.41, lng: 103.87, fact: 'O maior monumento religioso do mundo aparece na bandeira do país.' },
      { name: 'Monte Fuji', country: 'Japão', flag: '🇯🇵', cat: 'natureza', lat: 35.36, lng: 138.73, fact: 'É um vulcão ativo e o pico mais alto do Japão (3.776 m).' },
      { name: 'Torre de Pisa', country: 'Itália', flag: '🇮🇹', cat: 'turistico', lat: 43.72, lng: 10.4, fact: 'Começou a tombar ainda durante a construção, no século 12.' },
      { name: 'Alhambra', country: 'Espanha', flag: '🇪🇸', cat: 'turistico', lat: 37.18, lng: -3.59, fact: 'O palácio mourisco tem poesia esculpida nas paredes.' },
      { name: 'Castelo de Neuschwanstein', country: 'Alemanha', flag: '🇩🇪', cat: 'turistico', lat: 47.56, lng: 10.75, fact: 'Inspirou o castelo da Cinderela da Disney.' },
      { name: 'Monte Rushmore', country: 'Estados Unidos', flag: '🇺🇸', cat: 'turistico', lat: 43.88, lng: -103.46, fact: '400 trabalhadores esculpiram os presidentes por 14 anos.' },
      { name: 'Mont Saint-Michel', country: 'França', flag: '🇫🇷', cat: 'turistico', lat: 48.64, lng: -1.51, fact: 'A abadia vira uma ilha quando a maré sobe.' },
      { name: 'Borobudur', country: 'Indonésia', flag: '🇮🇩', cat: 'turistico', lat: -7.61, lng: 110.2, fact: 'O maior templo budista do mundo ficou séculos sob cinzas vulcânicas.' },
      { name: 'Abu Simbel', country: 'Egito', flag: '🇪🇬', cat: 'turistico', lat: 22.34, lng: 31.63, fact: 'O templo inteiro foi recortado e movido para escapar de uma represa.' },
      { name: 'Ponte Golden Gate', country: 'Estados Unidos', flag: '🇺🇸', cat: 'turistico', lat: 37.82, lng: -122.48, fact: 'Seus cabos somam 129 mil km de fios de aço.' },
      { name: 'Torres Petronas', country: 'Malásia', flag: '🇲🇾', cat: 'turistico', lat: 3.16, lng: 101.71, fact: 'Já foram os prédios mais altos do mundo, ligados por uma ponte no céu.' },
      { name: 'Templo Dourado de Kyoto', country: 'Japão', flag: '🇯🇵', cat: 'turistico', lat: 35.04, lng: 135.73, fact: 'O Kinkaku-ji é coberto por folhas de ouro de verdade.' },
      { name: 'Sagrada Família', country: 'Espanha', flag: '🇪🇸', cat: 'turistico', lat: 41.4, lng: 2.17, fact: 'Gaudí dizia que seu cliente, Deus, não tinha pressa.' },
      { name: 'Torre Eiffel', country: 'França', flag: '🇫🇷', cat: 'turistico', lat: 48.86, lng: 2.29, fact: 'Era para ser temporária e desmontada após 20 anos.' },
      { name: 'Opera House de Sydney', country: 'Austrália', flag: '🇦🇺', cat: 'turistico', lat: -33.86, lng: 151.21, fact: 'Levou 14 anos para ser construída — 10 a mais que o previsto.' },
      { name: 'Acrópole de Atenas', country: 'Grécia', flag: '🇬🇷', cat: 'turistico', lat: 37.97, lng: 23.73, fact: 'O Partenon não tem uma única linha perfeitamente reta.' },
      { name: 'Santorini', country: 'Grécia', flag: '🇬🇷', cat: 'turistico', lat: 36.39, lng: 25.46, fact: 'A ilha é a borda de uma cratera vulcânica submersa.' },
      { name: 'Cinque Terre', country: 'Itália', flag: '🇮🇹', cat: 'turistico', lat: 44.13, lng: 9.71, fact: 'Cinco vilarejos coloridos pendurados em falésias sobre o mar.' },
      { name: 'Hagia Sophia', country: 'Turquia', flag: '🇹🇷', cat: 'turistico', lat: 41.01, lng: 28.98, fact: 'Foi catedral, mesquita, museu — e mesquita de novo.' },
      { name: 'Palácio de Versalhes', country: 'França', flag: '🇫🇷', cat: 'turistico', lat: 48.8, lng: 2.12, fact: 'A Galeria dos Espelhos tem 357 espelhos e 73 metros.' },
      { name: 'Palácio de Potala', country: 'China (Tibete)', flag: '🇨🇳', cat: 'turistico', lat: 29.66, lng: 91.12, fact: 'O palácio dos Dalai Lamas tem 1.000 cômodos a 3.700 m de altitude.' },
      { name: 'Catedral de São Basílio', country: 'Rússia', flag: '🇷🇺', cat: 'turistico', lat: 55.75, lng: 37.62, fact: 'Suas cúpulas coloridas foram pintadas 200 anos após a construção.' },
      { name: 'Palácio de Buckingham', country: 'Reino Unido', flag: '🇬🇧', cat: 'turistico', lat: 51.5, lng: -0.14, fact: 'Tem 775 cômodos e um posto de gasolina próprio.' },
      { name: 'Museu Guggenheim de Bilbao', country: 'Espanha', flag: '🇪🇸', cat: 'turistico', lat: 43.27, lng: -2.93, fact: 'Suas curvas de titânio revitalizaram uma cidade industrial inteira.' },
      { name: 'Templo Dourado de Amritsar', country: 'Índia', flag: '🇮🇳', cat: 'turistico', lat: 31.62, lng: 74.88, fact: 'Serve refeição gratuita a até 100 mil pessoas por dia.' },
      { name: 'Cidade Proibida', country: 'China', flag: '🇨🇳', cat: 'turistico', lat: 39.92, lng: 116.39, fact: 'Por 500 anos, gente comum não podia entrar — daí o nome.' },
      { name: 'Exército de Terracota', country: 'China', flag: '🇨🇳', cat: 'turistico', lat: 34.38, lng: 109.28, fact: 'São 8 mil soldados e nenhum rosto se repete.' },
      { name: 'Templo de Karnak', country: 'Egito', flag: '🇪🇬', cat: 'turistico', lat: 25.72, lng: 32.66, fact: 'Levou 2 mil anos e 30 faraós para ficar pronto.' },
      { name: 'Pompeia', country: 'Itália', flag: '🇮🇹', cat: 'turistico', lat: 40.75, lng: 14.49, fact: 'As cinzas do Vesúvio congelaram a cidade no ano 79.' },
      { name: 'Dubrovnik', country: 'Croácia', flag: '🇭🇷', cat: 'turistico', lat: 42.64, lng: 18.11, fact: 'A "pérola do Adriático" virou Porto Real em Game of Thrones.' },
      { name: 'Meteora', country: 'Grécia', flag: '🇬🇷', cat: 'turistico', lat: 39.72, lng: 21.63, fact: 'Mosteiros construídos no topo de torres de rocha de 400 m.' },
      { name: 'Bruges', country: 'Bélgica', flag: '🇧🇪', cat: 'turistico', lat: 51.21, lng: 3.22, fact: 'A "Veneza do Norte" mantém o traçado medieval intacto.' },
      { name: 'Hallstatt', country: 'Áustria', flag: '🇦🇹', cat: 'turistico', lat: 47.56, lng: 13.65, fact: 'A vila alpina foi copiada inteira, em tamanho real, na China.' },
      { name: 'Teotihuacán', country: 'México', flag: '🇲🇽', cat: 'turistico', lat: 19.69, lng: -98.84, fact: 'Já estava em ruínas quando os astecas a encontraram.' },
      { name: 'Tikal', country: 'Guatemala', flag: '🇬🇹', cat: 'turistico', lat: 17.22, lng: -89.62, fact: 'As pirâmides maias despontam acima da copa da floresta.' },
      { name: 'Cataratas do Niágara', country: 'Canadá / EUA', flag: '🇨🇦', cat: 'natureza', lat: 43.08, lng: -79.07, fact: 'Já foram "desligadas" em 1969 para estudos de erosão.' },
      { name: 'Templo Wat Arun', country: 'Tailândia', flag: '🇹🇭', cat: 'turistico', lat: 13.74, lng: 100.49, fact: 'O "templo do amanhecer" é decorado com porcelana chinesa quebrada.' },
      { name: 'Torii de Itsukushima', country: 'Japão', flag: '🇯🇵', cat: 'turistico', lat: 34.3, lng: 132.32, fact: 'O portal vermelho parece flutuar no mar quando a maré sobe.' },
      { name: 'Muralha de Ávila', country: 'Espanha', flag: '🇪🇸', cat: 'turistico', lat: 40.66, lng: -4.7, fact: 'A muralha medieval mais bem preservada da Europa tem 88 torres.' },
      { name: 'Catedral de Colônia', country: 'Alemanha', flag: '🇩🇪', cat: 'turistico', lat: 50.94, lng: 6.96, fact: 'Levou 632 anos para ser concluída — com uma pausa de 300 anos.' },
    ],
  },
  {
    name: 'Cidades pelo Mundo',
    desc: 'Grandes cidades que não são capitais. Fica esperto!',
    time: 10,
    places: [
      { name: 'Osaka', country: 'Japão', flag: '🇯🇵', cat: 'cidade', lat: 34.69, lng: 135.5, fact: 'É conhecida como "a cozinha do Japão" pela comida de rua.' },
      { name: 'Joanesburgo', country: 'África do Sul', flag: '🇿🇦', cat: 'cidade', lat: -26.2, lng: 28.05, fact: 'É a maior cidade do mundo que não fica à beira de rio, lago ou mar.' },
      { name: 'Casablanca', country: 'Marrocos', flag: '🇲🇦', cat: 'cidade', lat: 33.57, lng: -7.59, fact: 'O filme clássico de 1942 não foi filmado lá: foi todo em estúdio.' },
      { name: 'Nova Orleans', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 29.95, lng: -90.07, fact: 'É o berço do jazz.' },
      { name: 'Seattle', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 47.61, lng: -122.33, fact: 'Nasceram lá a Starbucks, a Boeing e o grunge.' },
      { name: 'Boston', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 42.36, lng: -71.06, fact: 'Harvard, na região, é mais antiga que os próprios Estados Unidos.' },
      { name: 'Auckland', country: 'Nova Zelândia', flag: '🇳🇿', cat: 'cidade', lat: -36.85, lng: 174.76, fact: 'A cidade é construída sobre cerca de 50 vulcões.' },
      { name: 'Marselha', country: 'França', flag: '🇫🇷', cat: 'cidade', lat: 43.3, lng: 5.37, fact: 'A cidade mais antiga da França foi fundada por gregos há 2.600 anos.' },
      { name: 'Nápoles', country: 'Itália', flag: '🇮🇹', cat: 'cidade', lat: 40.85, lng: 14.27, fact: 'Berço da pizza, vive à sombra do vulcão Vesúvio.' },
      { name: 'Porto', country: 'Portugal', flag: '🇵🇹', cat: 'cidade', lat: 41.15, lng: -8.61, fact: 'Deu nome ao país e ao vinho do Porto.' },
      { name: 'Cusco', country: 'Peru', flag: '🇵🇪', cat: 'cidade', lat: -13.53, lng: -71.97, fact: 'Capital do império Inca; os muros originais seguem de pé.' },
      { name: 'Cartagena', country: 'Colômbia', flag: '🇨🇴', cat: 'cidade', lat: 10.39, lng: -75.51, fact: 'Muralhas de 400 anos ainda cercam o centro colonial.' },
      { name: 'Medellín', country: 'Colômbia', flag: '🇨🇴', cat: 'cidade', lat: 6.24, lng: -75.58, fact: 'É chamada de "cidade da eterna primavera" pelo clima.' },
      { name: 'Salvador', country: 'Brasil', flag: '🇧🇷', cat: 'cidade', lat: -12.97, lng: -38.5, fact: 'Foi a primeira capital do Brasil, por 214 anos.' },
      { name: 'Manaus', country: 'Brasil', flag: '🇧🇷', cat: 'cidade', lat: -3.12, lng: -60.02, fact: 'Um teatro de ópera italiano no meio da Amazônia.' },
      { name: 'Recife', country: 'Brasil', flag: '🇧🇷', cat: 'cidade', lat: -8.05, lng: -34.88, fact: 'A "Veneza brasileira" é cortada por rios e pontes.' },
      { name: 'Porto Alegre', country: 'Brasil', flag: '🇧🇷', cat: 'cidade', lat: -30.03, lng: -51.23, fact: 'Fica às margens do Guaíba, onde o pôr do sol é famoso.' },
      { name: 'Guadalajara', country: 'México', flag: '🇲🇽', cat: 'cidade', lat: 20.67, lng: -103.35, fact: 'Berço do mariachi e da tequila.' },
      { name: 'Monterrey', country: 'México', flag: '🇲🇽', cat: 'cidade', lat: 25.69, lng: -100.32, fact: 'Cercada pela Sierra Madre, é o polo industrial do México.' },
      { name: 'Montreal', country: 'Canadá', flag: '🇨🇦', cat: 'cidade', lat: 45.5, lng: -73.57, fact: 'A segunda maior cidade francófona do mundo, depois de Paris.' },
      { name: 'Calgary', country: 'Canadá', flag: '🇨🇦', cat: 'cidade', lat: 51.05, lng: -114.07, fact: 'Seu rodeio anual atrai mais de 1 milhão de pessoas.' },
      { name: 'Houston', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 29.76, lng: -95.37, fact: '"Houston" foi a primeira palavra dita da Lua.' },
      { name: 'Denver', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 39.74, lng: -104.99, fact: 'A "cidade a uma milha de altura" fica a exatos 1.609 m.' },
      { name: 'Filadélfia', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 39.95, lng: -75.17, fact: 'A independência dos EUA foi assinada lá em 1776.' },
      { name: 'Detroit', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 42.33, lng: -83.05, fact: 'A capital mundial do automóvel também criou o selo Motown.' },
      { name: 'Frankfurt', country: 'Alemanha', flag: '🇩🇪', cat: 'cidade', lat: 50.11, lng: 8.68, fact: 'O único skyline de arranha-céus da Alemanha.' },
      { name: 'Hamburgo', country: 'Alemanha', flag: '🇩🇪', cat: 'cidade', lat: 53.55, lng: 9.99, fact: 'Tem mais pontes que Veneza, Amsterdã e Londres somadas.' },
      { name: 'Lyon', country: 'França', flag: '🇫🇷', cat: 'cidade', lat: 45.76, lng: 4.84, fact: 'Considerada a capital gastronômica da França.' },
      { name: 'Nice', country: 'França', flag: '🇫🇷', cat: 'cidade', lat: 43.7, lng: 7.27, fact: 'A Promenade des Anglais foi paga por ingleses em 1820.' },
      { name: 'Sevilha', country: 'Espanha', flag: '🇪🇸', cat: 'cidade', lat: 37.39, lng: -5.99, fact: 'Tem cerca de 40 mil laranjeiras plantadas nas ruas.' },
      { name: 'Valência', country: 'Espanha', flag: '🇪🇸', cat: 'cidade', lat: 39.47, lng: -0.38, fact: 'Terra da paella, tem um parque construído no leito de um rio desviado.' },
      { name: 'Florença', country: 'Itália', flag: '🇮🇹', cat: 'cidade', lat: 43.77, lng: 11.26, fact: 'Berço do Renascimento e da família Médici.' },
      { name: 'Turim', country: 'Itália', flag: '🇮🇹', cat: 'cidade', lat: 45.07, lng: 7.69, fact: 'Foi a primeira capital da Itália unificada, em 1861.' },
      { name: 'Genebra', country: 'Suíça', flag: '🇨🇭', cat: 'cidade', lat: 46.2, lng: 6.14, fact: 'Sede europeia da ONU e do acelerador de partículas do CERN.' },
      { name: 'Zurique', country: 'Suíça', flag: '🇨🇭', cat: 'cidade', lat: 47.37, lng: 8.54, fact: 'Não é a capital, mas é o coração financeiro da Suíça.' },
      { name: 'Roterdã', country: 'Países Baixos', flag: '🇳🇱', cat: 'cidade', lat: 51.92, lng: 4.48, fact: 'Tem o maior porto da Europa.' },
      { name: 'Gotemburgo', country: 'Suécia', flag: '🇸🇪', cat: 'cidade', lat: 57.71, lng: 11.97, fact: 'A segunda maior cidade sueca foi projetada por holandeses.' },
      { name: 'Cracóvia', country: 'Polônia', flag: '🇵🇱', cat: 'cidade', lat: 50.06, lng: 19.94, fact: 'Foi capital da Polônia por mais de 500 anos.' },
      { name: 'São Petersburgo', country: 'Rússia', flag: '🇷🇺', cat: 'cidade', lat: 59.93, lng: 30.34, fact: 'No verão, as "noites brancas" quase não escurecem.' },
      { name: 'Odessa', country: 'Ucrânia', flag: '🇺🇦', cat: 'cidade', lat: 46.48, lng: 30.73, fact: 'Sua escadaria Potemkin tem 192 degraus e uma ilusão de ótica.' },
      { name: 'Esmirna', country: 'Turquia', flag: '🇹🇷', cat: 'cidade', lat: 38.42, lng: 27.14, fact: 'Izmir é uma das cidades mais antigas do Mediterrâneo.' },
      { name: 'Alexandria', country: 'Egito', flag: '🇪🇬', cat: 'cidade', lat: 31.2, lng: 29.92, fact: 'Sua biblioteca antiga tentou reunir todo o conhecimento do mundo.' },
      { name: 'Lagos', country: 'Nigéria', flag: '🇳🇬', cat: 'cidade', lat: 6.52, lng: 3.38, fact: 'É a maior cidade da África, com mais de 15 milhões de pessoas.' },
      { name: 'Marraquexe', country: 'Marrocos', flag: '🇲🇦', cat: 'cidade', lat: 31.63, lng: -8.0, fact: 'Sua praça Jemaa el-Fna vira um teatro a céu aberto toda noite.' },
      { name: 'Durban', country: 'África do Sul', flag: '🇿🇦', cat: 'cidade', lat: -29.86, lng: 31.02, fact: 'Tem a maior população indiana fora da Índia.' },
      { name: 'Chennai', country: 'Índia', flag: '🇮🇳', cat: 'cidade', lat: 13.08, lng: 80.27, fact: 'Marina Beach é uma das praias urbanas mais longas do mundo.' },
      { name: 'Bangalore', country: 'Índia', flag: '🇮🇳', cat: 'cidade', lat: 12.97, lng: 77.59, fact: 'É o Vale do Silício da Índia.' },
      { name: 'Cantão', country: 'China', flag: '🇨🇳', cat: 'cidade', lat: 23.13, lng: 113.26, fact: 'Guangzhou sedia a maior feira comercial da China desde 1957.' },
      { name: 'Busan', country: 'Coreia do Sul', flag: '🇰🇷', cat: 'cidade', lat: 35.18, lng: 129.08, fact: 'A segunda maior cidade coreana tem o maior mercado de peixes do país.' },
      { name: 'Perth', country: 'Austrália', flag: '🇦🇺', cat: 'cidade', lat: -31.95, lng: 115.86, fact: 'Uma das cidades mais isoladas do mundo: 2.100 km até a vizinha.' },
    ],
  },
  {
    name: 'Capitais Escondidas',
    desc: 'Capitais que pouca gente sabe apontar. O jogo começa a apertar.',
    time: 10,
    places: [
      { name: 'Ancara', country: 'Turquia', flag: '🇹🇷', cat: 'capital', lat: 39.93, lng: 32.86, fact: 'Muita gente acha que a capital é Istambul, mas é Ancara desde 1923.' },
      { name: 'Cartum', country: 'Sudão', flag: '🇸🇩', cat: 'capital', lat: 15.5, lng: 32.56, fact: 'É onde o Nilo Azul e o Nilo Branco se encontram e formam o Nilo.' },
      { name: 'Bratislava', country: 'Eslováquia', flag: '🇸🇰', cat: 'capital', lat: 48.15, lng: 17.11, fact: 'A única capital do mundo que faz fronteira com dois países.' },
      { name: 'Liubliana', country: 'Eslovênia', flag: '🇸🇮', cat: 'capital', lat: 46.06, lng: 14.51, fact: 'Um dragão é o símbolo da cidade e guarda sua ponte mais famosa.' },
      { name: 'Sarajevo', country: 'Bósnia e Herzegovina', flag: '🇧🇦', cat: 'capital', lat: 43.86, lng: 18.41, fact: 'O atentado que iniciou a 1ª Guerra Mundial aconteceu numa ponte da cidade.' },
      { name: 'Podgorica', country: 'Montenegro', flag: '🇲🇪', cat: 'capital', lat: 42.44, lng: 19.26, fact: 'Já se chamou Titogrado, em homenagem ao líder iugoslavo.' },
      { name: 'Skopje', country: 'Macedônia do Norte', flag: '🇲🇰', cat: 'capital', lat: 41.99, lng: 21.43, fact: 'Terra natal de Madre Teresa de Calcutá.' },
      { name: 'Tirana', country: 'Albânia', flag: '🇦🇱', cat: 'capital', lat: 41.33, lng: 19.82, fact: 'Um prefeito mandou pintar os prédios cinzentos de cores berrantes.' },
      { name: 'Pristina', country: 'Kosovo', flag: '🇽🇰', cat: 'capital', lat: 42.66, lng: 21.16, fact: 'Uma das capitais mais jovens do mundo: o país nasceu em 2008.' },
      { name: 'Chisinau', country: 'Moldávia', flag: '🇲🇩', cat: 'capital', lat: 47.01, lng: 28.86, fact: 'O país tem as maiores adegas subterrâneas do mundo.' },
      { name: 'Erevan', country: 'Armênia', flag: '🇦🇲', cat: 'capital', lat: 40.18, lng: 44.51, fact: 'É mais antiga que Roma — fundada em 782 a.C.' },
      { name: 'Tbilisi', country: 'Geórgia', flag: '🇬🇪', cat: 'capital', lat: 41.72, lng: 44.83, fact: 'Nasceu em volta de fontes de água quente naturais.' },
      { name: 'Reiquiavique', country: 'Islândia', flag: '🇮🇸', cat: 'capital', lat: 64.15, lng: -21.94, fact: 'A capital mais ao norte do mundo é aquecida por energia geotérmica.' },
      { name: 'Luxemburgo', country: 'Luxemburgo', flag: '🇱🇺', cat: 'capital', lat: 49.61, lng: 6.13, fact: 'Foi o primeiro país a tornar todo o transporte público gratuito.' },
      { name: 'Mônaco', country: 'Mônaco', flag: '🇲🇨', cat: 'capital', lat: 43.74, lng: 7.42, fact: 'O segundo menor país do mundo cabe no Central Park.' },
      { name: 'Andorra-a-Velha', country: 'Andorra', flag: '🇦🇩', cat: 'capital', lat: 42.51, lng: 1.52, fact: 'A capital mais alta da Europa fica encravada nos Pirineus.' },
      { name: 'Nicósia', country: 'Chipre', flag: '🇨🇾', cat: 'capital', lat: 35.17, lng: 33.36, fact: 'A última capital dividida do mundo, cortada por um muro ao meio.' },
      { name: 'Colombo', country: 'Sri Lanka', flag: '🇱🇰', cat: 'cidade', lat: 6.93, lng: 79.86, fact: 'O país tem duas capitais — e a oficial é a vizinha, quase impronunciável.' },
      { name: 'Daca', country: 'Bangladesh', flag: '🇧🇩', cat: 'capital', lat: 23.81, lng: 90.41, fact: 'É conhecida como a capital mundial dos riquixás.' },
      { name: 'Katmandu', country: 'Nepal', flag: '🇳🇵', cat: 'capital', lat: 27.72, lng: 85.32, fact: 'Sua região abriga 7 conjuntos de patrimônio mundial da UNESCO.' },
      { name: 'Phnom Penh', country: 'Camboja', flag: '🇰🇭', cat: 'capital', lat: 11.56, lng: 104.92, fact: 'Fica no encontro de três rios, incluindo o Mekong.' },
      { name: 'Taipé', country: 'Taiwan', flag: '🇹🇼', cat: 'capital', lat: 25.03, lng: 121.57, fact: 'O arranha-céu Taipei 101 tem um pêndulo gigante contra terremotos.' },
      { name: 'Pyongyang', country: 'Coreia do Norte', flag: '🇰🇵', cat: 'capital', lat: 39.02, lng: 125.74, fact: 'Tem o estádio de maior capacidade do mundo.' },
      { name: 'Manágua', country: 'Nicarágua', flag: '🇳🇮', cat: 'capital', lat: 12.11, lng: -86.24, fact: 'Um terremoto em 1972 destruiu 80% da cidade.' },
      { name: 'Tegucigalpa', country: 'Honduras', flag: '🇭🇳', cat: 'capital', lat: 14.07, lng: -87.19, fact: 'É uma das poucas capitais do mundo sem ferrovia.' },
      { name: 'San Salvador', country: 'El Salvador', flag: '🇸🇻', cat: 'capital', lat: 13.69, lng: -89.19, fact: 'Fica no "vale das hamacas", por causa dos tremores frequentes.' },
      { name: 'Cidade da Guatemala', country: 'Guatemala', flag: '🇬🇹', cat: 'capital', lat: 14.63, lng: -90.51, fact: 'É a maior cidade da América Central.' },
      { name: 'San José', country: 'Costa Rica', flag: '🇨🇷', cat: 'capital', lat: 9.93, lng: -84.08, fact: 'Foi uma das primeiras cidades do mundo a ter luz elétrica pública.' },
      { name: 'Cidade do Panamá', country: 'Panamá', flag: '🇵🇦', cat: 'capital', lat: 8.98, lng: -79.52, fact: 'A única capital do mundo com uma floresta tropical dentro dos limites.' },
      { name: 'Santo Domingo', country: 'República Dominicana', flag: '🇩🇴', cat: 'capital', lat: 18.49, lng: -69.93, fact: 'A cidade europeia mais antiga das Américas, fundada em 1496.' },
      { name: 'Porto Príncipe', country: 'Haiti', flag: '🇭🇹', cat: 'capital', lat: 18.59, lng: -72.31, fact: 'O Haiti foi a primeira república negra independente do mundo.' },
      { name: 'Kingston', country: 'Jamaica', flag: '🇯🇲', cat: 'capital', lat: 17.97, lng: -76.79, fact: 'Berço do reggae e de Bob Marley.' },
      { name: 'Nassau', country: 'Bahamas', flag: '🇧🇸', cat: 'capital', lat: 25.06, lng: -77.35, fact: 'Foi um famoso refúgio de piratas no século 18.' },
      { name: 'Belmopan', country: 'Belize', flag: '🇧🇿', cat: 'capital', lat: 17.25, lng: -88.77, fact: 'Criada em 1970 depois que um furacão devastou a antiga capital.' },
      { name: 'Luanda', country: 'Angola', flag: '🇦🇴', cat: 'capital', lat: -8.84, lng: 13.23, fact: 'Já foi eleita a cidade mais cara do mundo para estrangeiros.' },
      { name: 'Maputo', country: 'Moçambique', flag: '🇲🇿', cat: 'capital', lat: -25.97, lng: 32.57, fact: 'Tem uma estação de trem projetada pelo escritório de Gustave Eiffel.' },
      { name: 'Harare', country: 'Zimbábue', flag: '🇿🇼', cat: 'capital', lat: -17.83, lng: 31.05, fact: 'Fica num planalto a 1.490 m, o que suaviza o calor tropical.' },
      { name: 'Lusaka', country: 'Zâmbia', flag: '🇿🇲', cat: 'capital', lat: -15.39, lng: 28.32, fact: 'Cresceu ao redor de uma estação ferroviária construída em 1905.' },
      { name: 'Kampala', country: 'Uganda', flag: '🇺🇬', cat: 'capital', lat: 0.35, lng: 32.58, fact: 'Construída sobre sete colinas, às margens do lago Vitória.' },
      { name: 'Dar es Salaam', country: 'Tanzânia', flag: '🇹🇿', cat: 'cidade', lat: -6.79, lng: 39.21, fact: 'A maior cidade da Tanzânia perdeu o posto de capital para Dodoma.' },
      { name: 'Mogadíscio', country: 'Somália', flag: '🇸🇴', cat: 'capital', lat: 2.04, lng: 45.34, fact: 'Foi um dos portos mais movimentados do oceano Índico.' },
      { name: 'Asmara', country: 'Eritreia', flag: '🇪🇷', cat: 'capital', lat: 15.34, lng: 38.93, fact: 'Sua arquitetura art déco italiana é patrimônio da UNESCO.' },
      { name: 'Juba', country: 'Sudão do Sul', flag: '🇸🇸', cat: 'capital', lat: 4.85, lng: 31.58, fact: 'Capital do país mais novo do mundo, nascido em 2011.' },
      { name: 'Kinshasa', country: 'RD Congo', flag: '🇨🇩', cat: 'capital', lat: -4.32, lng: 15.31, fact: 'Fica de frente para Brazzaville: as duas capitais mais próximas do mundo.' },
      { name: 'Abidjan', country: 'Costa do Marfim', flag: '🇨🇮', cat: 'cidade', lat: 5.36, lng: -4.01, fact: 'A maior cidade do país perdeu o posto de capital para Yamoussoukro.' },
      { name: 'Yaoundé', country: 'Camarões', flag: '🇨🇲', cat: 'capital', lat: 3.87, lng: 11.52, fact: 'A "cidade das sete colinas" fica cercada de montanhas vulcânicas.' },
      { name: 'Antananarivo', country: 'Madagascar', flag: '🇲🇬', cat: 'capital', lat: -18.88, lng: 47.51, fact: '90% das espécies de Madagascar não existem em nenhum outro lugar.' },
      { name: 'Ulaanbaatar', country: 'Mongólia', flag: '🇲🇳', cat: 'capital', lat: 47.89, lng: 106.91, fact: 'É a capital mais fria do mundo: média anual abaixo de 0 °C.' },
      { name: 'Baku', country: 'Azerbaijão', flag: '🇦🇿', cat: 'capital', lat: 40.41, lng: 49.87, fact: 'É a capital mais baixa do mundo: 28 m abaixo do nível do mar.' },
      { name: 'Muscat', country: 'Omã', flag: '🇴🇲', cat: 'capital', lat: 23.59, lng: 58.41, fact: 'Nenhum prédio pode ser mais alto que uma palmeira — quase.' },
    ],
  },
  {
    name: 'Maravilhas Naturais',
    desc: 'A natureza não tem endereço. Boa sorte!',
    time: 10,
    places: [
      { name: 'Grand Canyon', country: 'Estados Unidos', flag: '🇺🇸', cat: 'natureza', lat: 36.11, lng: -112.11, fact: 'O rio Colorado levou cerca de 6 milhões de anos esculpindo o cânion.' },
      { name: 'Cataratas do Iguaçu', country: 'Brasil / Argentina', flag: '🇧🇷', cat: 'natureza', lat: -25.69, lng: -54.44, fact: 'São 275 quedas d’água em quase 3 km de extensão.' },
      { name: 'Cataratas Vitória', country: 'Zâmbia / Zimbábue', flag: '🇿🇲', cat: 'natureza', lat: -17.92, lng: 25.86, fact: 'O nome local significa "a fumaça que troveja".' },
      { name: 'Monte Everest', country: 'Nepal / China', flag: '🇳🇵', cat: 'natureza', lat: 27.99, lng: 86.93, fact: 'Cresce cerca de 4 mm por ano — e seu topo tem fósseis marinhos.' },
      { name: 'Monte Kilimanjaro', country: 'Tanzânia', flag: '🇹🇿', cat: 'natureza', lat: -3.07, lng: 37.36, fact: 'A montanha mais alta do mundo que não faz parte de uma cordilheira.' },
      { name: 'Uluru', country: 'Austrália', flag: '🇦🇺', cat: 'natureza', lat: -25.34, lng: 131.04, fact: 'A rocha gigante muda de cor ao longo do dia, do ocre ao vermelho vivo.' },
      { name: 'Salar de Uyuni', country: 'Bolívia', flag: '🇧🇴', cat: 'natureza', lat: -20.13, lng: -67.49, fact: 'O maior deserto de sal do mundo vira um espelho gigante quando chove.' },
      { name: 'Grande Barreira de Corais', country: 'Austrália', flag: '🇦🇺', cat: 'natureza', lat: -18.29, lng: 147.7, fact: 'É o maior ser vivo da Terra: dá para ver do espaço.' },
      { name: 'Lago Baikal', country: 'Rússia', flag: '🇷🇺', cat: 'natureza', lat: 53.5, lng: 108.0, fact: 'Guarda 20% de toda a água doce líquida do planeta.' },
      { name: 'Ilhas Galápagos', country: 'Equador', flag: '🇪🇨', cat: 'natureza', lat: -0.74, lng: -90.35, fact: 'Foi lá que Darwin teve as ideias que viraram a teoria da evolução.' },
      { name: 'Lençóis Maranhenses', country: 'Brasil', flag: '🇧🇷', cat: 'natureza', lat: -2.56, lng: -43.06, fact: 'Dunas brancas com lagoas azuis — e chove demais para ser deserto.' },
      { name: 'Milford Sound', country: 'Nova Zelândia', flag: '🇳🇿', cat: 'natureza', lat: -44.67, lng: 167.93, fact: 'Kipling chamou o fiorde de "oitava maravilha do mundo".' },
      { name: 'Deserto do Atacama', country: 'Chile', flag: '🇨🇱', cat: 'natureza', lat: -24.5, lng: -69.25, fact: 'O lugar mais seco da Terra: há estações que nunca registraram chuva.' },
      { name: 'Pantanal', country: 'Brasil', flag: '🇧🇷', cat: 'natureza', lat: -17.7, lng: -57.4, fact: 'É a maior planície alagável do planeta.' },
      { name: 'Fernando de Noronha', country: 'Brasil', flag: '🇧🇷', cat: 'natureza', lat: -3.85, lng: -32.42, fact: 'Há limite diário de visitantes para proteger o arquipélago.' },
      { name: 'Chapada Diamantina', country: 'Brasil', flag: '🇧🇷', cat: 'natureza', lat: -12.6, lng: -41.4, fact: 'Suas grutas têm poços de água azul fluorescente.' },
      { name: 'Yellowstone', country: 'Estados Unidos', flag: '🇺🇸', cat: 'natureza', lat: 44.43, lng: -110.59, fact: 'O primeiro parque nacional do mundo (1872) fica sobre um supervulcão.' },
      { name: 'Yosemite', country: 'Estados Unidos', flag: '🇺🇸', cat: 'natureza', lat: 37.75, lng: -119.59, fact: 'O paredão El Capitan tem 900 m de rocha vertical.' },
      { name: 'Vale da Morte', country: 'Estados Unidos', flag: '🇺🇸', cat: 'natureza', lat: 36.5, lng: -117.08, fact: 'Registrou 56,7 °C, a maior temperatura já medida na Terra.' },
      { name: 'Antelope Canyon', country: 'Estados Unidos', flag: '🇺🇸', cat: 'natureza', lat: 36.86, lng: -111.37, fact: 'A luz que entra pelas fendas cria feixes que parecem sólidos.' },
      { name: 'Banff', country: 'Canadá', flag: '🇨🇦', cat: 'natureza', lat: 51.18, lng: -115.57, fact: 'Os lagos azul-turquesa devem a cor ao pó de rocha das geleiras.' },
      { name: 'Denali', country: 'Estados Unidos', flag: '🇺🇸', cat: 'natureza', lat: 63.07, lng: -151.01, fact: 'O pico mais alto da América do Norte cria seu próprio clima.' },
      { name: 'Matterhorn', country: 'Suíça / Itália', flag: '🇨🇭', cat: 'natureza', lat: 45.98, lng: 7.66, fact: 'É a montanha do logotipo do chocolate Toblerone.' },
      { name: 'Mont Blanc', country: 'França / Itália', flag: '🇫🇷', cat: 'natureza', lat: 45.83, lng: 6.86, fact: 'O ponto mais alto dos Alpes muda de altura conforme a neve do ano.' },
      { name: 'Geirangerfjord', country: 'Noruega', flag: '🇳🇴', cat: 'natureza', lat: 62.1, lng: 7.09, fact: 'Cachoeiras despencam direto das paredes do fiorde.' },
      { name: 'Vatnajökull', country: 'Islândia', flag: '🇮🇸', cat: 'natureza', lat: 64.41, lng: -16.83, fact: 'A maior geleira da Europa esconde vulcões ativos embaixo.' },
      { name: 'Lagos de Plitvice', country: 'Croácia', flag: '🇭🇷', cat: 'natureza', lat: 44.88, lng: 15.61, fact: 'São 16 lagos ligados por cachoeiras que mudam de cor.' },
      { name: 'Penhascos de Moher', country: 'Irlanda', flag: '🇮🇪', cat: 'natureza', lat: 52.97, lng: -9.43, fact: 'Falésias de 214 m caindo direto no Atlântico.' },
      { name: 'Calçada dos Gigantes', country: 'Reino Unido', flag: '🇬🇧', cat: 'natureza', lat: 55.24, lng: -6.51, fact: '40 mil colunas hexagonais formadas por lava resfriada.' },
      { name: 'Monte Etna', country: 'Itália', flag: '🇮🇹', cat: 'natureza', lat: 37.75, lng: 14.99, fact: 'O vulcão mais ativo da Europa entra em erupção quase todo ano.' },
      { name: 'Pamukkale', country: 'Turquia', flag: '🇹🇷', cat: 'natureza', lat: 37.92, lng: 29.12, fact: '"Castelo de algodão": terraços brancos de travertino com água termal.' },
      { name: 'Capadócia', country: 'Turquia', flag: '🇹🇷', cat: 'natureza', lat: 38.64, lng: 34.83, fact: 'Esconde cidades subterrâneas de até 18 andares escavadas na rocha.' },
      { name: 'Mar Morto', country: 'Israel / Jordânia', flag: '🇮🇱', cat: 'natureza', lat: 31.5, lng: 35.47, fact: 'O ponto mais baixo em terra firme: 430 m abaixo do nível do mar.' },
      { name: 'Wadi Rum', country: 'Jordânia', flag: '🇯🇴', cat: 'natureza', lat: 29.58, lng: 35.42, fact: 'O "vale da lua" já fez o papel de Marte em vários filmes.' },
      { name: 'Erg Chebbi', country: 'Marrocos', flag: '🇲🇦', cat: 'natureza', lat: 31.15, lng: -3.98, fact: 'Dunas de até 150 m na porta de entrada do Saara.' },
      { name: 'Sossusvlei', country: 'Namíbia', flag: '🇳🇦', cat: 'natureza', lat: -24.73, lng: 15.34, fact: 'Dunas vermelhas de até 380 m, entre as mais altas do mundo.' },
      { name: 'Delta do Okavango', country: 'Botsuana', flag: '🇧🇼', cat: 'natureza', lat: -19.28, lng: 22.81, fact: 'Um rio que não chega ao mar: evapora no meio do deserto.' },
      { name: 'Serengeti', country: 'Tanzânia', flag: '🇹🇿', cat: 'natureza', lat: -2.33, lng: 34.83, fact: 'Palco da maior migração terrestre do planeta: 1,5 milhão de gnus.' },
      { name: 'Cratera de Ngorongoro', country: 'Tanzânia', flag: '🇹🇿', cat: 'natureza', lat: -3.17, lng: 35.58, fact: 'Uma cratera vulcânica virou um zoológico natural de 260 km².' },
      { name: 'Monte Sinai', country: 'Egito', flag: '🇪🇬', cat: 'natureza', lat: 28.54, lng: 33.97, fact: 'Peregrinos sobem de madrugada para ver o nascer do sol no cume.' },
      { name: 'Baía de Ha Long', country: 'Vietnã', flag: '🇻🇳', cat: 'natureza', lat: 20.91, lng: 107.18, fact: 'Quase 2.000 ilhas de calcário que, diz a lenda, foram cuspidas por dragões.' },
      { name: 'Zhangjiajie', country: 'China', flag: '🇨🇳', cat: 'natureza', lat: 29.32, lng: 110.43, fact: 'Os pilares de pedra inspiraram as montanhas flutuantes de Avatar.' },
      { name: 'Guilin', country: 'China', flag: '🇨🇳', cat: 'natureza', lat: 25.27, lng: 110.29, fact: 'As montanhas cársticas do rio Li estampam a nota de 20 yuans.' },
      { name: 'Monte Bromo', country: 'Indonésia', flag: '🇮🇩', cat: 'natureza', lat: -7.94, lng: 112.95, fact: 'O vulcão fuma dentro de um "mar de areia" de outra cratera.' },
      { name: 'Ilha de Komodo', country: 'Indonésia', flag: '🇮🇩', cat: 'natureza', lat: -8.55, lng: 119.49, fact: 'Único lugar do mundo com dragões-de-komodo em liberdade.' },
      { name: 'Bora Bora', country: 'Polinésia Francesa', flag: '🇵🇫', cat: 'natureza', lat: -16.5, lng: -151.74, fact: 'A ilha é o que sobrou de um vulcão extinto cercado por corais.' },
      { name: 'Torres del Paine', country: 'Chile', flag: '🇨🇱', cat: 'natureza', lat: -50.94, lng: -73.4, fact: 'Três torres de granito de 2.500 m no meio da Patagônia.' },
      { name: 'Perito Moreno', country: 'Argentina', flag: '🇦🇷', cat: 'natureza', lat: -50.5, lng: -73.19, fact: 'Uma das raras geleiras do mundo que ainda avança.' },
      { name: 'Lago Titicaca', country: 'Peru / Bolívia', flag: '🇵🇪', cat: 'natureza', lat: -15.77, lng: -69.38, fact: 'O lago navegável mais alto do mundo tem ilhas flutuantes de junco.' },
      { name: 'Grande Buraco Azul', country: 'Belize', flag: '🇧🇿', cat: 'natureza', lat: 17.32, lng: -87.53, fact: 'Um sumidouro submarino de 318 m de diâmetro e 124 m de profundidade.' },
    ],
  },
  {
    name: 'Cantos Remotos',
    desc: 'Fim do mundo. Aqui, errar por 500 km já é vitória.',
    time: 10,
    places: [
      { name: 'Ushuaia', country: 'Argentina', flag: '🇦🇷', cat: 'cidade', lat: -54.8, lng: -68.3, fact: 'A cidade mais austral do mundo, porta de saída para a Antártida.' },
      { name: 'Timbuktu', country: 'Mali', flag: '🇲🇱', cat: 'cidade', lat: 16.77, lng: -3.01, fact: 'No século 14 era um dos maiores centros de conhecimento do planeta.' },
      { name: 'Nuuk', country: 'Groenlândia', flag: '🇬🇱', cat: 'capital', lat: 64.18, lng: -51.72, fact: 'Capital de um território gigante com só 57 mil habitantes.' },
      { name: 'Honolulu', country: 'Estados Unidos (Havaí)', flag: '🇺🇸', cat: 'cidade', lat: 21.31, lng: -157.86, fact: 'A grande cidade mais isolada do mundo: 3.800 km até o continente.' },
      { name: 'Ilha de Páscoa', country: 'Chile', flag: '🇨🇱', cat: 'turistico', lat: -27.11, lng: -109.35, fact: 'Os moais têm corpo inteiro enterrado — não são só cabeças.' },
      { name: 'Longyearbyen', country: 'Noruega (Svalbard)', flag: '🇳🇴', cat: 'cidade', lat: 78.22, lng: 15.63, fact: 'A cidade mais ao norte do mundo tem mais ursos-polares que gente.' },
      { name: 'Suva', country: 'Fiji', flag: '🇫🇯', cat: 'capital', lat: -18.14, lng: 178.44, fact: 'Fiji tem mais de 330 ilhas — e só um terço é habitado.' },
      { name: 'Ponta Delgada', country: 'Portugal (Açores)', flag: '🇵🇹', cat: 'cidade', lat: 37.74, lng: -25.67, fact: 'Fica no meio do Atlântico, sobre o encontro de 3 placas tectônicas.' },
      { name: 'Tórshavn', country: 'Ilhas Faroé', flag: '🇫🇴', cat: 'capital', lat: 62.01, lng: -6.77, fact: 'Nas Faroé, as ovelhas são mais numerosas que as pessoas.' },
      { name: 'Stanley', country: 'Ilhas Malvinas', flag: '🇫🇰', cat: 'capital', lat: -51.69, lng: -57.86, fact: 'Nas ilhas há muito mais pinguins que habitantes.' },
      { name: 'Anchorage', country: 'Estados Unidos (Alasca)', flag: '🇺🇸', cat: 'cidade', lat: 61.22, lng: -149.9, fact: 'Alces passeiam tranquilamente pelas ruas da cidade.' },
      { name: 'Yakutsk', country: 'Rússia', flag: '🇷🇺', cat: 'cidade', lat: 62.03, lng: 129.73, fact: 'A grande cidade mais fria do mundo: inverno médio de −40 °C.' },
      { name: 'Darwin', country: 'Austrália', flag: '🇦🇺', cat: 'cidade', lat: -12.46, lng: 130.84, fact: 'Fica mais perto de Jacarta do que de Sydney.' },
      { name: 'Papeete', country: 'Polinésia Francesa', flag: '🇵🇫', cat: 'cidade', lat: -17.53, lng: -149.57, fact: 'Fica a mais de 15 mil km da França, que a governa.' },
      { name: 'Malé', country: 'Maldivas', flag: '🇲🇻', cat: 'capital', lat: 4.18, lng: 73.51, fact: 'O país inteiro fica, em média, a só 1 metro acima do mar.' },
      { name: 'Apia', country: 'Samoa', flag: '🇼🇸', cat: 'capital', lat: -13.83, lng: -171.77, fact: 'Samoa pulou um dia inteiro em 2011 ao trocar de fuso horário.' },
      { name: 'Nouméa', country: 'Nova Caledônia', flag: '🇳🇨', cat: 'cidade', lat: -22.28, lng: 166.46, fact: 'É cercada pela maior lagoa do mundo.' },
      { name: 'Iqaluit', country: 'Canadá (Nunavut)', flag: '🇨🇦', cat: 'cidade', lat: 63.75, lng: -68.52, fact: 'Não há estradas ligando a cidade ao resto do Canadá.' },
      { name: 'Punta Arenas', country: 'Chile', flag: '🇨🇱', cat: 'cidade', lat: -53.16, lng: -70.91, fact: 'Fica à beira do Estreito de Magalhães, na Patagônia.' },
      { name: 'Socotra', country: 'Iêmen', flag: '🇾🇪', cat: 'natureza', lat: 12.51, lng: 53.92, fact: 'Tem árvores "sangue-de-dragão" que não existem em mais lugar nenhum.' },
      { name: 'Tristão da Cunha', country: 'Reino Unido', flag: '🇬🇧', cat: 'cidade', lat: -37.11, lng: -12.28, fact: 'O arquipélago habitado mais isolado do mundo: 2.400 km até o vizinho.' },
      { name: 'Santa Helena', country: 'Reino Unido', flag: '🇬🇧', cat: 'cidade', lat: -15.96, lng: -5.72, fact: 'Napoleão morreu exilado nesta ilha perdida no Atlântico Sul.' },
      { name: 'Ilhas Pitcairn', country: 'Reino Unido', flag: '🇵🇳', cat: 'cidade', lat: -25.07, lng: -130.1, fact: 'Habitada por descendentes dos amotinados do Bounty: menos de 50 pessoas.' },
      { name: 'Ilha Ascensão', country: 'Reino Unido', flag: '🇦🇨', cat: 'cidade', lat: -7.95, lng: -14.36, fact: 'Um vulcão no meio do Atlântico usado como base aérea e rastreio espacial.' },
      { name: 'Ilhas Kerguelen', country: 'França', flag: '🇹🇫', cat: 'natureza', lat: -49.35, lng: 70.22, fact: 'Chamadas de "ilhas da desolação": ninguém mora lá permanentemente.' },
      { name: 'Geórgia do Sul', country: 'Reino Unido', flag: '🇬🇸', cat: 'natureza', lat: -54.28, lng: -36.5, fact: 'Tem colônias com centenas de milhares de pinguins-rei.' },
      { name: 'Ittoqqortoormiit', country: 'Groenlândia', flag: '🇬🇱', cat: 'cidade', lat: 70.48, lng: -21.97, fact: 'Cerca de 350 moradores e o maior parque nacional do mundo ao lado.' },
      { name: 'Utqiagvik', country: 'Estados Unidos (Alasca)', flag: '🇺🇸', cat: 'cidade', lat: 71.29, lng: -156.79, fact: 'O sol não nasce por 65 dias seguidos no inverno.' },
      { name: 'Yellowknife', country: 'Canadá', flag: '🇨🇦', cat: 'cidade', lat: 62.45, lng: -114.37, fact: 'Um dos melhores lugares do planeta para ver a aurora boreal.' },
      { name: 'Whitehorse', country: 'Canadá', flag: '🇨🇦', cat: 'cidade', lat: 60.72, lng: -135.06, fact: 'Tem o ar menos poluído do mundo, segundo o Guinness.' },
      { name: 'Unalaska', country: 'Estados Unidos (Aleutas)', flag: '🇺🇸', cat: 'cidade', lat: 53.87, lng: -166.54, fact: 'Porto pesqueiro numa cadeia de ilhas vulcânicas no meio do Pacífico.' },
      { name: 'Murmansk', country: 'Rússia', flag: '🇷🇺', cat: 'cidade', lat: 68.97, lng: 33.09, fact: 'A maior cidade do mundo acima do Círculo Polar Ártico.' },
      { name: 'Norilsk', country: 'Rússia', flag: '🇷🇺', cat: 'cidade', lat: 69.35, lng: 88.2, fact: 'Cidade fechada a estrangeiros, construída sobre permafrost.' },
      { name: 'Magadan', country: 'Rússia', flag: '🇷🇺', cat: 'cidade', lat: 59.56, lng: 150.8, fact: 'Porto no mar de Okhotsk, ponto final de uma estrada tenebrosa.' },
      { name: 'Petropavlovsk-Kamchatsky', country: 'Rússia', flag: '🇷🇺', cat: 'cidade', lat: 53.04, lng: 158.65, fact: 'Cercada por vulcões, só é acessível de avião ou barco.' },
      { name: 'Díli', country: 'Timor-Leste', flag: '🇹🇱', cat: 'capital', lat: -8.56, lng: 125.56, fact: 'Capital de um dos países mais jovens da Ásia, independente em 2002.' },
      { name: 'Port Moresby', country: 'Papua-Nova Guiné', flag: '🇵🇬', cat: 'capital', lat: -9.44, lng: 147.18, fact: 'No país se falam mais de 800 idiomas — recorde absoluto.' },
      { name: 'Honiara', country: 'Ilhas Salomão', flag: '🇸🇧', cat: 'capital', lat: -9.43, lng: 159.95, fact: 'A ilha de Guadalcanal foi palco de batalhas decisivas em 1942.' },
      { name: 'Alice Springs', country: 'Austrália', flag: '🇦🇺', cat: 'cidade', lat: -23.7, lng: 133.88, fact: 'No centro exato do deserto australiano, a 1.500 km do mar.' },
      { name: 'Coober Pedy', country: 'Austrália', flag: '🇦🇺', cat: 'cidade', lat: -29.01, lng: 134.75, fact: 'Metade dos moradores vive em casas subterrâneas por causa do calor.' },
      { name: 'Ilhas Chatham', country: 'Nova Zelândia', flag: '🇳🇿', cat: 'cidade', lat: -43.95, lng: -176.56, fact: 'Um dos primeiros lugares habitados do mundo a ver o ano novo.' },
      { name: 'Ilha Norfolk', country: 'Austrália', flag: '🇳🇫', cat: 'cidade', lat: -29.04, lng: 167.95, fact: 'Seus pinheiros altíssimos aparecem na bandeira da ilha.' },
      { name: 'Ilhas Cocos', country: 'Austrália', flag: '🇨🇨', cat: 'natureza', lat: -12.19, lng: 96.83, fact: 'Dois atóis com 600 habitantes no meio do oceano Índico.' },
      { name: 'Ilha Christmas', country: 'Austrália', flag: '🇨🇽', cat: 'natureza', lat: -10.49, lng: 105.62, fact: 'Todo ano, 50 milhões de caranguejos vermelhos cruzam a ilha.' },
      { name: 'Praia', country: 'Cabo Verde', flag: '🇨🇻', cat: 'capital', lat: 14.93, lng: -23.51, fact: 'Capital de um arquipélago vulcânico a 570 km da África.' },
      { name: 'São Tomé', country: 'São Tomé e Príncipe', flag: '🇸🇹', cat: 'capital', lat: 0.34, lng: 6.73, fact: 'O segundo menor país da África fica quase em cima da linha do Equador.' },
      { name: 'Ilha da Reunião', country: 'França', flag: '🇷🇪', cat: 'natureza', lat: -21.11, lng: 55.53, fact: 'Tem um dos vulcões mais ativos do mundo, o Piton de la Fournaise.' },
      { name: 'Zanzibar', country: 'Tanzânia', flag: '🇹🇿', cat: 'cidade', lat: -6.16, lng: 39.19, fact: 'A ilha das especiarias foi o maior entreposto de cravo do mundo.' },
      { name: 'Ilhas Aland', country: 'Finlândia', flag: '🇦🇽', cat: 'cidade', lat: 60.1, lng: 19.94, fact: 'Arquipélago de 6.700 ilhas onde se fala sueco, não finlandês.' },
      { name: 'Ilha de Man', country: 'Reino Unido', flag: '🇮🇲', cat: 'cidade', lat: 54.24, lng: -4.55, fact: 'Tem o parlamento em funcionamento contínuo mais antigo do mundo.' },
    ],
  },
  {
    name: 'Nível Lenda',
    desc: 'Capitais que nem o Google acha de primeira. Respira e crava rápido.',
    time: 10,
    places: [
      { name: 'Funafuti', country: 'Tuvalu', flag: '🇹🇻', cat: 'capital', lat: -8.52, lng: 179.2, fact: 'Capital de um dos países menos visitados do mundo: ~2 mil turistas/ano.' },
      { name: 'Thimphu', country: 'Butão', flag: '🇧🇹', cat: 'capital', lat: 27.47, lng: 89.64, fact: 'Uma das duas únicas capitais do mundo sem nenhum semáforo.' },
      { name: 'Maseru', country: 'Lesoto', flag: '🇱🇸', cat: 'capital', lat: -29.31, lng: 27.48, fact: 'Lesoto é um país inteiramente cercado pela África do Sul.' },
      { name: 'Mbabane', country: 'Essuatíni', flag: '🇸🇿', cat: 'capital', lat: -26.31, lng: 31.14, fact: 'O país trocou de nome em 2018: era Suazilândia.' },
      { name: 'Bandar Seri Begawan', country: 'Brunei', flag: '🇧🇳', cat: 'capital', lat: 4.94, lng: 114.95, fact: 'Tem uma vila inteira sobre palafitas: a "Veneza do Oriente".' },
      { name: 'Paramaribo', country: 'Suriname', flag: '🇸🇷', cat: 'capital', lat: 5.85, lng: -55.2, fact: 'O idioma oficial do vizinho do Brasil é… holandês.' },
      { name: 'Georgetown', country: 'Guiana', flag: '🇬🇾', cat: 'capital', lat: 6.8, lng: -58.16, fact: 'Fica abaixo do nível do mar, protegida por diques.' },
      { name: 'Djibuti', country: 'Djibuti', flag: '🇩🇯', cat: 'capital', lat: 11.59, lng: 43.15, fact: 'O lago Assal, ali perto, é o ponto mais baixo da África.' },
      { name: 'Bishkek', country: 'Quirguistão', flag: '🇰🇬', cat: 'capital', lat: 42.87, lng: 74.59, fact: 'O Quirguistão é 90% montanhas — quase tudo acima de 1.500 m.' },
      { name: 'Valeta', country: 'Malta', flag: '🇲🇹', cat: 'capital', lat: 35.9, lng: 14.51, fact: 'A menor capital da União Europeia se atravessa a pé em 15 minutos.' },
      { name: 'Port Vila', country: 'Vanuatu', flag: '🇻🇺', cat: 'capital', lat: -17.73, lng: 168.32, fact: 'Em Vanuatu existe um culto que venera o príncipe Philip.' },
      { name: 'Moroni', country: 'Comores', flag: '🇰🇲', cat: 'capital', lat: -11.7, lng: 43.26, fact: 'As Comores são o maior produtor mundial de ylang-ylang.' },
      { name: 'Achgabat', country: 'Turcomenistão', flag: '🇹🇲', cat: 'capital', lat: 37.96, lng: 58.33, fact: 'Detém o recorde mundial de prédios revestidos de mármore branco.' },
      { name: 'Dushanbe', country: 'Tadjiquistão', flag: '🇹🇯', cat: 'capital', lat: 38.56, lng: 68.79, fact: 'O nome significa "segunda-feira": a cidade nasceu de uma feira semanal.' },
      { name: 'Tashkent', country: 'Uzbequistão', flag: '🇺🇿', cat: 'capital', lat: 41.3, lng: 69.24, fact: 'Fotografar seu metrô, cheio de lustres, foi proibido até 2018.' },
      { name: 'Astana', country: 'Cazaquistão', flag: '🇰🇿', cat: 'capital', lat: 51.17, lng: 71.43, fact: 'Capital planejada na estepe, com invernos de −35 °C.' },
      { name: 'Naypyidaw', country: 'Mianmar', flag: '🇲🇲', cat: 'capital', lat: 19.75, lng: 96.1, fact: 'Construída em segredo, tem rodovias de 20 pistas quase vazias.' },
      { name: 'Vientiane', country: 'Laos', flag: '🇱🇦', cat: 'capital', lat: 17.97, lng: 102.6, fact: 'À beira do Mekong, é uma das capitais mais tranquilas da Ásia.' },
      { name: 'Gaborone', country: 'Botsuana', flag: '🇧🇼', cat: 'capital', lat: -24.65, lng: 25.91, fact: 'Uma das capitais que mais cresceram no mundo desde 1966.' },
      { name: 'Windhoek', country: 'Namíbia', flag: '🇳🇦', cat: 'capital', lat: -22.56, lng: 17.08, fact: 'Guarda forte herança alemã no meio do deserto da Namíbia.' },
      { name: 'Lilongwe', country: 'Malaui', flag: '🇲🇼', cat: 'capital', lat: -13.98, lng: 33.79, fact: 'O lago Malawi tem mais espécies de peixes que qualquer outro lago.' },
      { name: 'Nouakchott', country: 'Mauritânia', flag: '🇲🇷', cat: 'capital', lat: 18.09, lng: -15.98, fact: 'Era uma vila de pescadores em 1958; hoje tem 1 milhão de habitantes.' },
      { name: 'Banjul', country: 'Gâmbia', flag: '🇬🇲', cat: 'capital', lat: 13.45, lng: -16.58, fact: 'A capital fica numa ilha na foz do rio Gâmbia.' },
      { name: 'Bissau', country: 'Guiné-Bissau', flag: '🇬🇼', cat: 'capital', lat: 11.86, lng: -15.6, fact: 'O país tem um arquipélago com 88 ilhas, quase todas desertas.' },
      { name: 'Conacri', country: 'Guiné', flag: '🇬🇳', cat: 'capital', lat: 9.64, lng: -13.58, fact: 'Construída numa península estreita de apenas 36 km².' },
      { name: 'Freetown', country: 'Serra Leoa', flag: '🇸🇱', cat: 'capital', lat: 8.48, lng: -13.23, fact: 'Fundada em 1792 por escravizados libertos.' },
      { name: 'Monróvia', country: 'Libéria', flag: '🇱🇷', cat: 'capital', lat: 6.31, lng: -10.8, fact: 'Única capital do mundo batizada em homenagem a um presidente dos EUA.' },
      { name: 'Yamoussoukro', country: 'Costa do Marfim', flag: '🇨🇮', cat: 'capital', lat: 6.83, lng: -5.29, fact: 'Tem a maior igreja do mundo, maior que a Basílica de São Pedro.' },
      { name: 'Lomé', country: 'Togo', flag: '🇹🇬', cat: 'capital', lat: 6.13, lng: 1.22, fact: 'A capital fica colada na fronteira com Gana.' },
      { name: 'Porto-Novo', country: 'Benin', flag: '🇧🇯', cat: 'capital', lat: 6.5, lng: 2.63, fact: 'É a capital oficial, mas o governo funciona em Cotonou.' },
      { name: 'Niamey', country: 'Níger', flag: '🇳🇪', cat: 'capital', lat: 13.51, lng: 2.11, fact: 'Às margens do rio Níger, na borda sul do Saara.' },
      { name: 'Uagadugu', country: 'Burkina Faso', flag: '🇧🇫', cat: 'capital', lat: 12.37, lng: -1.53, fact: 'Sedia o maior festival de cinema da África.' },
      { name: 'Bamako', country: 'Mali', flag: '🇲🇱', cat: 'capital', lat: 12.65, lng: -8.0, fact: 'Uma das cidades que mais crescem no mundo, às margens do Níger.' },
      { name: "N'Djamena", country: 'Chade', flag: '🇹🇩', cat: 'capital', lat: 12.11, lng: 15.04, fact: 'O lago Chade, ali perto, encolheu 90% em 60 anos.' },
      { name: 'Bangui', country: 'República Centro-Africana', flag: '🇨🇫', cat: 'capital', lat: 4.39, lng: 18.56, fact: 'Fica às margens do rio Ubangi, na fronteira com o Congo.' },
      { name: 'Libreville', country: 'Gabão', flag: '🇬🇦', cat: 'capital', lat: 0.42, lng: 9.47, fact: 'Quase 90% do Gabão é coberto por floresta tropical.' },
      { name: 'Malabo', country: 'Guiné Equatorial', flag: '🇬🇶', cat: 'capital', lat: 3.75, lng: 8.78, fact: 'A capital fica numa ilha, longe da parte continental do país.' },
      { name: 'Gitega', country: 'Burundi', flag: '🇧🇮', cat: 'capital', lat: -3.43, lng: 29.93, fact: 'Virou capital em 2019, no lugar de Bujumbura.' },
      { name: 'Kigali', country: 'Ruanda', flag: '🇷🇼', cat: 'capital', lat: -1.94, lng: 30.06, fact: 'Uma das capitais mais limpas da África: sacolas plásticas são proibidas.' },
      { name: 'Dodoma', country: 'Tanzânia', flag: '🇹🇿', cat: 'capital', lat: -6.16, lng: 35.75, fact: 'Virou capital em 1974, mas quase tudo continua em Dar es Salaam.' },
      { name: 'Victoria', country: 'Seicheles', flag: '🇸🇨', cat: 'capital', lat: -4.62, lng: 55.45, fact: 'Uma das menores capitais do mundo, com cerca de 25 mil habitantes.' },
      { name: 'Port Louis', country: 'Maurício', flag: '🇲🇺', cat: 'capital', lat: -20.16, lng: 57.5, fact: 'Seu mercado central funciona desde a época vitoriana.' },
      { name: 'Tarawa', country: 'Kiribati', flag: '🇰🇮', cat: 'capital', lat: 1.33, lng: 172.98, fact: 'Kiribati foi o primeiro país a entrar no ano 2000.' },
      { name: 'Majuro', country: 'Ilhas Marshall', flag: '🇲🇭', cat: 'capital', lat: 7.09, lng: 171.38, fact: 'O atol tem lugares com menos de 100 m de largura.' },
      { name: 'Palikir', country: 'Micronésia', flag: '🇫🇲', cat: 'capital', lat: 6.92, lng: 158.16, fact: 'Perto dali fica Nan Madol, uma cidade construída sobre recifes.' },
      { name: 'Ngerulmud', country: 'Palau', flag: '🇵🇼', cat: 'capital', lat: 7.5, lng: 134.62, fact: 'A capital menos populosa do mundo tem cerca de 400 moradores.' },
      { name: 'Yaren', country: 'Nauru', flag: '🇳🇷', cat: 'capital', lat: -0.55, lng: 166.92, fact: 'Nauru é o menor país insular do mundo: 21 km².' },
      { name: "Nuku'alofa", country: 'Tonga', flag: '🇹🇴', cat: 'capital', lat: -21.14, lng: -175.2, fact: 'Tonga é o único reino do Pacífico que nunca foi colonizado.' },
      { name: 'Basseterre', country: 'São Cristóvão e Neves', flag: '🇰🇳', cat: 'capital', lat: 17.3, lng: -62.72, fact: 'Capital do menor país das Américas em área e população.' },
      { name: "St. George's", country: 'Granada', flag: '🇬🇩', cat: 'capital', lat: 12.06, lng: -61.75, fact: 'A "ilha das especiarias" produz boa parte da noz-moscada do mundo.' },
    ],
  },
];
