/* Banco de lugares do "Cadê no Mapa?"
 * Cada nível tem um pool de 12 lugares; a cada partida o jogo sorteia 5.
 * lat/lng em graus decimais. cat: capital | cidade | turistico | natureza
 */
window.LEVELS = [
  {
    name: 'Gigantes do Mapa',
    desc: 'Cidades que todo mundo conhece. Aquecimento!',
    time: 10,
    places: [
      { name: 'Rio de Janeiro', country: 'Brasil', flag: '🇧🇷', cat: 'cidade', lat: -22.91, lng: -43.17, fact: 'Tem a maior floresta urbana do mundo, a Floresta da Tijuca.' },
      { name: 'Paris', country: 'França', flag: '🇫🇷', cat: 'cidade', lat: 48.86, lng: 2.35, fact: 'A Torre Eiffel cresce até 15 cm no verão por causa do calor.' },
      { name: 'Nova York', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 40.71, lng: -74.01, fact: 'Mais de 800 idiomas são falados na cidade — recorde mundial.' },
      { name: 'Londres', country: 'Reino Unido', flag: '🇬🇧', cat: 'cidade', lat: 51.51, lng: -0.13, fact: 'O Big Ben é o nome do sino, não da torre.' },
      { name: 'Tóquio', country: 'Japão', flag: '🇯🇵', cat: 'capital', lat: 35.68, lng: 139.69, fact: 'É a maior região metropolitana do mundo: mais de 37 milhões de pessoas.' },
      { name: 'Sydney', country: 'Austrália', flag: '🇦🇺', cat: 'cidade', lat: -33.87, lng: 151.21, fact: 'A Opera House tem mais de 1 milhão de telhas no telhado.' },
      { name: 'Moscou', country: 'Rússia', flag: '🇷🇺', cat: 'capital', lat: 55.76, lng: 37.62, fact: 'O metrô de Moscou é tão bonito que é chamado de "palácio subterrâneo".' },
      { name: 'Cairo', country: 'Egito', flag: '🇪🇬', cat: 'capital', lat: 30.04, lng: 31.24, fact: 'É a maior cidade da África e do mundo árabe.' },
      { name: 'Roma', country: 'Itália', flag: '🇮🇹', cat: 'capital', lat: 41.9, lng: 12.5, fact: 'Jogam cerca de 1,5 milhão de euros por ano na Fontana di Trevi.' },
      { name: 'Pequim', country: 'China', flag: '🇨🇳', cat: 'capital', lat: 39.9, lng: 116.4, fact: 'A Cidade Proibida tem 8.700 salas e quase 1 milhão de relíquias.' },
      { name: 'Buenos Aires', country: 'Argentina', flag: '🇦🇷', cat: 'capital', lat: -34.6, lng: -58.38, fact: 'Tem a avenida mais larga do mundo: a 9 de Julio, com 16 pistas.' },
      { name: 'Cidade do México', country: 'México', flag: '🇲🇽', cat: 'capital', lat: 19.43, lng: -99.13, fact: 'Foi construída sobre um lago e afunda cerca de 50 cm por ano.' },
    ],
  },
  {
    name: 'Capitais Famosas',
    desc: 'Capitais que aparecem no noticiário. Mais 5 rodadas!',
    time: 10,
    places: [
      { name: 'Washington, D.C.', country: 'Estados Unidos', flag: '🇺🇸', cat: 'capital', lat: 38.91, lng: -77.04, fact: 'Nenhum prédio pode ser mais alto que o Capitólio, por lei.' },
      { name: 'Berlim', country: 'Alemanha', flag: '🇩🇪', cat: 'capital', lat: 52.52, lng: 13.4, fact: 'Tem mais pontes que Veneza: cerca de 1.700.' },
      { name: 'Madri', country: 'Espanha', flag: '🇪🇸', cat: 'capital', lat: 40.42, lng: -3.7, fact: 'Abriga o restaurante mais antigo do mundo em funcionamento (1725).' },
      { name: 'Lisboa', country: 'Portugal', flag: '🇵🇹', cat: 'capital', lat: 38.72, lng: -9.14, fact: 'É mais antiga que Roma: tem mais de 3 mil anos.' },
      { name: 'Brasília', country: 'Brasil', flag: '🇧🇷', cat: 'capital', lat: -15.79, lng: -47.88, fact: 'Foi construída em apenas 41 meses e vista do alto tem forma de avião.' },
      { name: 'Ottawa', country: 'Canadá', flag: '🇨🇦', cat: 'capital', lat: 45.42, lng: -75.7, fact: 'No inverno, o canal Rideau vira a maior pista de patinação do mundo.' },
      { name: 'Canberra', country: 'Austrália', flag: '🇦🇺', cat: 'capital', lat: -35.28, lng: 149.13, fact: 'Foi criada do zero para acabar com a briga entre Sydney e Melbourne.' },
      { name: 'Nova Délhi', country: 'Índia', flag: '🇮🇳', cat: 'capital', lat: 28.61, lng: 77.21, fact: 'Délhi já foi capital de pelo menos 7 impérios diferentes.' },
      { name: 'Bangkok', country: 'Tailândia', flag: '🇹🇭', cat: 'capital', lat: 13.76, lng: 100.5, fact: 'Seu nome cerimonial completo tem 168 letras — o mais longo do mundo.' },
      { name: 'Atenas', country: 'Grécia', flag: '🇬🇷', cat: 'capital', lat: 37.98, lng: 23.73, fact: 'É habitada continuamente há mais de 5 mil anos.' },
      { name: 'Dublin', country: 'Irlanda', flag: '🇮🇪', cat: 'capital', lat: 53.35, lng: -6.26, fact: 'O portão da cervejaria Guinness tem contrato de aluguel de 9 mil anos.' },
      { name: 'Seul', country: 'Coreia do Sul', flag: '🇰🇷', cat: 'capital', lat: 37.57, lng: 126.98, fact: 'Metade da população da Coreia do Sul vive na sua região metropolitana.' },
    ],
  },
  {
    name: 'Cartões-Postais',
    desc: 'Pontos turísticos clássicos. Sem dica de país agora!',
    time: 10,
    places: [
      { name: 'Machu Picchu', country: 'Peru', flag: '🇵🇪', cat: 'turistico', lat: -13.16, lng: -72.55, fact: 'Foi construída no século 15 sem uso de rodas nem argamassa.' },
      { name: 'Cristo Redentor', country: 'Brasil', flag: '🇧🇷', cat: 'turistico', lat: -22.95, lng: -43.21, fact: 'É atingido por raios de 3 a 5 vezes por ano.' },
      { name: 'Grande Muralha da China', country: 'China', flag: '🇨🇳', cat: 'turistico', lat: 40.36, lng: 116.02, fact: 'Com todos os ramais, soma mais de 21 mil km de extensão.' },
      { name: 'Pirâmides de Gizé', country: 'Egito', flag: '🇪🇬', cat: 'turistico', lat: 29.98, lng: 31.13, fact: 'A Grande Pirâmide foi a construção mais alta do mundo por 3.800 anos.' },
      { name: 'Taj Mahal', country: 'Índia', flag: '🇮🇳', cat: 'turistico', lat: 27.17, lng: 78.04, fact: 'É um mausoléu construído por um imperador para a esposa favorita.' },
      { name: 'Stonehenge', country: 'Reino Unido', flag: '🇬🇧', cat: 'turistico', lat: 51.18, lng: -1.83, fact: 'Algumas pedras vieram de 250 km de distância — ninguém sabe como.' },
      { name: 'Coliseu', country: 'Itália', flag: '🇮🇹', cat: 'turistico', lat: 41.89, lng: 12.49, fact: 'Podia ser inundado para simular batalhas navais.' },
      { name: 'Estátua da Liberdade', country: 'Estados Unidos', flag: '🇺🇸', cat: 'turistico', lat: 40.69, lng: -74.04, fact: 'Foi um presente da França e chegou desmontada em 350 pedaços.' },
      { name: 'Chichén Itzá', country: 'México', flag: '🇲🇽', cat: 'turistico', lat: 20.68, lng: -88.57, fact: 'Bater palmas diante da pirâmide produz eco que imita um pássaro sagrado.' },
      { name: 'Petra', country: 'Jordânia', flag: '🇯🇴', cat: 'turistico', lat: 30.33, lng: 35.44, fact: 'A cidade inteira foi esculpida diretamente na rocha rosa.' },
      { name: 'Angkor Wat', country: 'Camboja', flag: '🇰🇭', cat: 'turistico', lat: 13.41, lng: 103.87, fact: 'É o maior monumento religioso do mundo e aparece na bandeira do país.' },
      { name: 'Monte Fuji', country: 'Japão', flag: '🇯🇵', cat: 'natureza', lat: 35.36, lng: 138.73, fact: 'É um vulcão ativo e o pico mais alto do Japão (3.776 m).' },
    ],
  },
  {
    name: 'Cidades pelo Mundo',
    desc: 'Grandes cidades que não são capitais. Fica esperto!',
    time: 10,
    places: [
      { name: 'Barcelona', country: 'Espanha', flag: '🇪🇸', cat: 'cidade', lat: 41.39, lng: 2.17, fact: 'A basílica da Sagrada Família está em obras desde 1882.' },
      { name: 'São Francisco', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 37.77, lng: -122.42, fact: 'A ponte Golden Gate é repintada continuamente, o ano inteiro.' },
      { name: 'Vancouver', country: 'Canadá', flag: '🇨🇦', cat: 'cidade', lat: 49.28, lng: -123.12, fact: 'Dá para esquiar e velejar no mesmo dia na cidade.' },
      { name: 'Milão', country: 'Itália', flag: '🇮🇹', cat: 'cidade', lat: 45.46, lng: 9.19, fact: 'Sua catedral gótica levou quase 600 anos para ficar pronta.' },
      { name: 'Munique', country: 'Alemanha', flag: '🇩🇪', cat: 'cidade', lat: 48.14, lng: 11.58, fact: 'A Oktoberfest começa, na verdade, em setembro.' },
      { name: 'Xangai', country: 'China', flag: '🇨🇳', cat: 'cidade', lat: 31.23, lng: 121.47, fact: 'Tem o trem comercial mais rápido do mundo: o Maglev, a 431 km/h.' },
      { name: 'Mumbai', country: 'Índia', flag: '🇮🇳', cat: 'cidade', lat: 19.08, lng: 72.88, fact: 'Produz mais filmes por ano que Hollywood — é a casa de Bollywood.' },
      { name: 'Osaka', country: 'Japão', flag: '🇯🇵', cat: 'cidade', lat: 34.69, lng: 135.5, fact: 'É conhecida como "a cozinha do Japão" pela comida de rua.' },
      { name: 'Joanesburgo', country: 'África do Sul', flag: '🇿🇦', cat: 'cidade', lat: -26.2, lng: 28.05, fact: 'É a maior cidade do mundo que não fica à beira de rio, lago ou mar.' },
      { name: 'Casablanca', country: 'Marrocos', flag: '🇲🇦', cat: 'cidade', lat: 33.57, lng: -7.59, fact: 'O filme clássico de 1942 não foi filmado lá: foi todo em estúdio.' },
      { name: 'Istambul', country: 'Turquia', flag: '🇹🇷', cat: 'cidade', lat: 41.01, lng: 28.98, fact: 'É a única grande cidade do mundo em dois continentes ao mesmo tempo.' },
      { name: 'Miami', country: 'Estados Unidos', flag: '🇺🇸', cat: 'cidade', lat: 25.76, lng: -80.19, fact: 'É a única grande cidade dos EUA fundada por uma mulher.' },
    ],
  },
  {
    name: 'Capitais Escondidas',
    desc: 'Capitais que pouca gente sabe apontar no mapa.',
    time: 10,
    places: [
      { name: 'Oslo', country: 'Noruega', flag: '🇳🇴', cat: 'capital', lat: 59.91, lng: 10.75, fact: 'Entrega o Prêmio Nobel da Paz todo ano desde 1901.' },
      { name: 'Helsinque', country: 'Finlândia', flag: '🇫🇮', cat: 'capital', lat: 60.17, lng: 24.94, fact: 'Tem uma igreja escavada dentro de uma rocha gigante.' },
      { name: 'Varsóvia', country: 'Polônia', flag: '🇵🇱', cat: 'capital', lat: 52.23, lng: 21.01, fact: 'Seu centro histórico foi reconstruído tijolo por tijolo após a guerra.' },
      { name: 'Budapeste', country: 'Hungria', flag: '🇭🇺', cat: 'capital', lat: 47.5, lng: 19.04, fact: 'São duas cidades, Buda e Peste, separadas pelo rio Danúbio.' },
      { name: 'Nairóbi', country: 'Quênia', flag: '🇰🇪', cat: 'capital', lat: -1.29, lng: 36.82, fact: 'Tem um parque nacional com leões e girafas dentro da cidade.' },
      { name: 'Lima', country: 'Peru', flag: '🇵🇪', cat: 'capital', lat: -12.05, lng: -77.04, fact: 'É a segunda maior cidade do mundo construída em um deserto.' },
      { name: 'Bogotá', country: 'Colômbia', flag: '🇨🇴', cat: 'capital', lat: 4.71, lng: -74.07, fact: 'Fica a 2.640 m de altitude, uma das capitais mais altas do mundo.' },
      { name: 'Hanói', country: 'Vietnã', flag: '🇻🇳', cat: 'capital', lat: 21.03, lng: 105.85, fact: 'Tem uma rua onde o trem passa a centímetros das casas.' },
      { name: 'Manila', country: 'Filipinas', flag: '🇵🇭', cat: 'capital', lat: 14.6, lng: 120.98, fact: 'É a cidade com maior densidade populacional do planeta.' },
      { name: 'Wellington', country: 'Nova Zelândia', flag: '🇳🇿', cat: 'capital', lat: -41.29, lng: 174.78, fact: 'É a capital mais ao sul do mundo — e a mais ventosa.' },
      { name: 'Ancara', country: 'Turquia', flag: '🇹🇷', cat: 'capital', lat: 39.93, lng: 32.86, fact: 'Muita gente acha que a capital é Istambul, mas é Ancara desde 1923.' },
      { name: 'Cartum', country: 'Sudão', flag: '🇸🇩', cat: 'capital', lat: 15.5, lng: 32.56, fact: 'É onde o Nilo Azul e o Nilo Branco se encontram e formam o rio Nilo.' },
    ],
  },
  {
    name: 'Maravilhas Naturais',
    desc: 'A natureza não tem endereço. Boa sorte!',
    time: 10,
    places: [
      { name: 'Grand Canyon', country: 'Estados Unidos', flag: '🇺🇸', cat: 'natureza', lat: 36.11, lng: -112.11, fact: 'O rio Colorado levou cerca de 6 milhões de anos esculpindo o cânion.' },
      { name: 'Cataratas do Iguaçu', country: 'Brasil / Argentina', flag: '🇧🇷', cat: 'natureza', lat: -25.69, lng: -54.44, fact: 'São 275 quedas d’água — quase o dobro da largura das cataratas do Niágara.' },
      { name: 'Cataratas Vitória', country: 'Zâmbia / Zimbábue', flag: '🇿🇲', cat: 'natureza', lat: -17.92, lng: 25.86, fact: 'O nome local significa "a fumaça que troveja".' },
      { name: 'Monte Everest', country: 'Nepal / China', flag: '🇳🇵', cat: 'natureza', lat: 27.99, lng: 86.93, fact: 'Cresce cerca de 4 mm por ano — e seu topo tem fósseis marinhos.' },
      { name: 'Monte Kilimanjaro', country: 'Tanzânia', flag: '🇹🇿', cat: 'natureza', lat: -3.07, lng: 37.36, fact: 'É a montanha mais alta do mundo que não faz parte de uma cordilheira.' },
      { name: 'Uluru', country: 'Austrália', flag: '🇦🇺', cat: 'natureza', lat: -25.34, lng: 131.04, fact: 'A rocha gigante muda de cor ao longo do dia, do ocre ao vermelho vivo.' },
      { name: 'Salar de Uyuni', country: 'Bolívia', flag: '🇧🇴', cat: 'natureza', lat: -20.13, lng: -67.49, fact: 'O maior deserto de sal do mundo vira um espelho gigante quando chove.' },
      { name: 'Grande Barreira de Corais', country: 'Austrália', flag: '🇦🇺', cat: 'natureza', lat: -18.29, lng: 147.7, fact: 'É o maior ser vivo da Terra: dá para ver do espaço.' },
      { name: 'Lago Baikal', country: 'Rússia', flag: '🇷🇺', cat: 'natureza', lat: 53.5, lng: 108.0, fact: 'Guarda 20% de toda a água doce líquida do planeta.' },
      { name: 'Ilhas Galápagos', country: 'Equador', flag: '🇪🇨', cat: 'natureza', lat: -0.74, lng: -90.35, fact: 'Foi lá que Darwin teve as ideias que viraram a teoria da evolução.' },
      { name: 'Lençóis Maranhenses', country: 'Brasil', flag: '🇧🇷', cat: 'natureza', lat: -2.56, lng: -43.06, fact: 'Dunas brancas com lagoas azuis — e tecnicamente nem é um deserto: chove muito lá.' },
      { name: 'Milford Sound', country: 'Nova Zelândia', flag: '🇳🇿', cat: 'natureza', lat: -44.67, lng: 167.93, fact: 'Um fiorde tão bonito que Kipling o chamou de "oitava maravilha do mundo".' },
    ],
  },
  {
    name: 'Cantos Remotos',
    desc: 'Fim do mundo. Só os fortes acertam a menos de 500 km.',
    time: 10,
    places: [
      { name: 'Reykjavík', country: 'Islândia', flag: '🇮🇸', cat: 'capital', lat: 64.15, lng: -21.94, fact: 'É a capital mais ao norte do mundo — aquecida por energia geotérmica.' },
      { name: 'Ushuaia', country: 'Argentina', flag: '🇦🇷', cat: 'cidade', lat: -54.8, lng: -68.3, fact: 'A cidade mais austral do mundo, porta de saída para a Antártida.' },
      { name: 'Timbuktu', country: 'Mali', flag: '🇲🇱', cat: 'cidade', lat: 16.77, lng: -3.01, fact: 'No século 14 era um dos maiores centros de conhecimento do planeta.' },
      { name: 'Ulaanbaatar', country: 'Mongólia', flag: '🇲🇳', cat: 'capital', lat: 47.89, lng: 106.91, fact: 'É a capital mais fria do mundo: média anual abaixo de 0 °C.' },
      { name: 'Kathmandu', country: 'Nepal', flag: '🇳🇵', cat: 'capital', lat: 27.72, lng: 85.32, fact: 'Sua região abriga 7 conjuntos de patrimônio mundial da UNESCO.' },
      { name: 'Nuuk', country: 'Groenlândia', flag: '🇬🇱', cat: 'capital', lat: 64.18, lng: -51.72, fact: 'Capital de um território gigante com só 57 mil habitantes.' },
      { name: 'Honolulu', country: 'Estados Unidos (Havaí)', flag: '🇺🇸', cat: 'cidade', lat: 21.31, lng: -157.86, fact: 'É a grande cidade mais isolada do mundo: a 3.800 km do continente.' },
      { name: 'Ilha de Páscoa', country: 'Chile', flag: '🇨🇱', cat: 'turistico', lat: -27.11, lng: -109.35, fact: 'Os moais têm corpo inteiro enterrado — não são só cabeças.' },
      { name: 'Antananarivo', country: 'Madagascar', flag: '🇲🇬', cat: 'capital', lat: -18.88, lng: 47.51, fact: '90% das espécies de Madagascar não existem em nenhum outro lugar.' },
      { name: 'Longyearbyen', country: 'Noruega (Svalbard)', flag: '🇳🇴', cat: 'cidade', lat: 78.22, lng: 15.63, fact: 'A cidade mais ao norte do mundo, onde há mais ursos-polares que pessoas.' },
      { name: 'Suva', country: 'Fiji', flag: '🇫🇯', cat: 'capital', lat: -18.14, lng: 178.44, fact: 'Fiji tem mais de 330 ilhas — e só um terço é habitado.' },
      { name: 'Ponta Delgada', country: 'Portugal (Açores)', flag: '🇵🇹', cat: 'cidade', lat: 37.74, lng: -25.67, fact: 'Fica no meio do Atlântico, em cima do encontro de 3 placas tectônicas.' },
    ],
  },
  {
    name: 'Nível Lenda',
    desc: 'Capitais que nem o Google acha de primeira. Respira e crava rápido.',
    time: 10,
    places: [
      { name: 'Funafuti', country: 'Tuvalu', flag: '🇹🇻', cat: 'capital', lat: -8.52, lng: 179.2, fact: 'Capital de um dos países menos visitados do mundo: ~2 mil turistas/ano.' },
      { name: 'Thimphu', country: 'Butão', flag: '🇧🇹', cat: 'capital', lat: 27.47, lng: 89.64, fact: 'Uma das duas únicas capitais do mundo sem nenhum semáforo.' },
      { name: 'Maseru', country: 'Lesoto', flag: '🇱🇸', cat: 'capital', lat: -29.31, lng: 27.48, fact: 'Lesoto é um país inteiramente cercado pela África do Sul.' },
      { name: 'Bandar Seri Begawan', country: 'Brunei', flag: '🇧🇳', cat: 'capital', lat: 4.94, lng: 114.95, fact: 'Tem uma vila inteira construída sobre palafitas: a "Veneza do Oriente".' },
      { name: 'Paramaribo', country: 'Suriname', flag: '🇸🇷', cat: 'capital', lat: 5.85, lng: -55.2, fact: 'O idioma oficial do vizinho do Brasil é… holandês.' },
      { name: 'Djibuti', country: 'Djibuti', flag: '🇩🇯', cat: 'capital', lat: 11.59, lng: 43.15, fact: 'O lago Assal, ali perto, é o ponto mais baixo da África: 155 m abaixo do mar.' },
      { name: 'Nicósia', country: 'Chipre', flag: '🇨🇾', cat: 'capital', lat: 35.19, lng: 33.38, fact: 'A última capital dividida do mundo, cortada por um muro ao meio.' },
      { name: 'Baku', country: 'Azerbaijão', flag: '🇦🇿', cat: 'capital', lat: 40.41, lng: 49.87, fact: 'É a capital mais baixa do mundo: 28 m abaixo do nível do mar.' },
      { name: 'Bishkek', country: 'Quirguistão', flag: '🇰🇬', cat: 'capital', lat: 42.87, lng: 74.59, fact: 'O Quirguistão é 90% montanhas — quase tudo acima de 1.500 m.' },
      { name: 'Valeta', country: 'Malta', flag: '🇲🇹', cat: 'capital', lat: 35.9, lng: 14.51, fact: 'É a menor capital da União Europeia: dá para atravessar a pé em 15 minutos.' },
      { name: 'Port Vila', country: 'Vanuatu', flag: '🇻🇺', cat: 'capital', lat: -17.73, lng: 168.32, fact: 'Em Vanuatu existe um culto que venera o príncipe Philip como divindade.' },
      { name: 'Moroni', country: 'Comores', flag: '🇰🇲', cat: 'capital', lat: -11.7, lng: 43.26, fact: 'As Comores são o maior produtor mundial de ylang-ylang, flor de perfumes.' },
    ],
  },
];
